### PR TITLE
fix: missing tool calling usage

### LINKED ISSUE #4440: [BUG]: No `usage` in response when tool calling
When a tool calling response is returned, there is no token usage in the response

* with tool calling

```
  "usage": null
```

* without tool calling

```
  "usage": {
    "prompt_tokens": 21,
    "completion_tokens": 406,
    "total_tokens": 427
  }
```

vllm serve has usage for both with / without tool calling

### PR DESCRIPTION
**Pull request by ayushag-nv**
#### Overview:

Issue: Usage was null whenever tool calling was enabled

Root Cause: Jailstream was skipping the chunks with just usage and no choices. 

This PR fixes that behaviour

#### Related Issues: (use one of the action keywords Closes / Fixes / Resolves / Relates to)

- closes #4440 

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed handling of API responses containing data but no choices to preserve metadata and response fields. Previously, such edge-case responses could be altered or handled inconsistently. Now they are yielded unchanged, ensuring complete information preservation across all response types.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by rmccorm4 — COMMENTED** [review]
Thanks Ayush! Can you fix the failing lint checks: https://github.com/ai-dynamo/dynamo/actions/runs/19552681877/job/55987859062?pr=4516?

File: lib/llm/src/protocols/openai/chat_completions/jail.rs [hunk 1]
```diff
@@ -555,6 +555,10 @@ impl JailedStream {
                                 yield emitted_response;
                             }
                         }
+                    } else if chat_response.choices.is_empty() {
+                        // No choices processed (e.g., usage-only chunk)
+                        // Pass through as-is to preserve usage and other metadata
+                        yield response;
```
Comment (rmccorm4) [inline lib/llm/src/protocols/openai/chat_completions/jail.rs]: Is this condition related to `all_emissions` at all? It feels a little strange as an else-if here because the conditions seem unrelated:
```rust
if let Some(chat_response) = response.data.as_ref() {
  // ...

  // If there are choices, process each individually
  for choice in &chat_response.choices {
    // ...
  
    if !all_emissions.is_empty() {
      // ... // big block of code
    } else if chat_response.choices.is_empty() {
      yield response
    }
  }
}
```

I'm wondering if it is still logically correct to move this further up the function for easier readability:
```rust
if let Some(chat_response) = response.data.as_ref() {
  // ...

  // If no choices processed (e.g., usage-only chunk)
  // Pass through as-is to preserve usage and other metadata
  if chat_response.choices.is_empty() {
    yield response
  }
  
  // If there are choices, process each individually
  for choice in &chat_response.choices {
    // ...
    if !all_emissions.is_empty() {
      // ... // big block of code
    }
  }
}
```

Let me know if this logical structure makes sense to you

Comment (ayushag-nv) [reply lib/llm/src/protocols/openai/chat_completions/jail.rs]: done

**Review by rmccorm4 — APPROVED** [review]

**Comment by rmccorm4** [comment]
/ok to test [e47a0d3](https://github.com/ai-dynamo/dynamo/pull/4516/commits/e47a0d37a5fea15abb0dd515e9f73666d4da7662)

**Comment by rmccorm4** [comment]
@ayushag-nv am I correct in understanding that this was only with tool calling with `stream=true`, and tool calling with `stream=false` was returning a non-null usage field even without this change?
