### PR TITLE
fix: dynamo-run change python subprocess from debug to info

### LINKED ISSUE #1422: [BUG]: Python errors and stack traces are logged as DEBUG level in dynamo run
### Describe the Bug

See title

### Steps to Reproduce

Set the DYN_LOG to INFO
```bash
export DYN_LOG=INFO
```
Run dynamo run with `http` in and `vllm` out
```
dynamo run in=http out=vllm deepseek-ai/DeepSeek-R1-Distill-Llama-8B
```

Suspend the process
```
Ctrl-Z
```

Run dynamo with in=text out=vllm
```
dynamo run in=text out=vllm deepseek-ai/DeepSeek-R1-Distill-Llama-8B
```

Do not observe error logs

Repeat the same steps with `DYN_LOG=DEBUG` and observe the python errors.

### Expected Behavior

See the Python ERROR logs

### Actual Behavior

Python ERROR logs only visible on DEBUG logging

### Environment

Fresh clone of main repo, `container/build.sh`, `containter/run.sh`. Follow instructions

### Additional Context

<details>
<summary><b>Dynamo Debug Logs 1</b></summary>

    2025-06-06T19:02:34.086Z DEBUG dynamo_run::subprocess: 2025-06-06T19:02:34.086Z  INFO model_runner.load_model: Starting to load model /root/.cache/huggingface/hub/models--deepseek-ai--DeepSeek-R1-Distill-Llama-8B/snapshots/6a6f4aa4197940add57724a7707d069478df56b1...   
    2025-06-06T19:02:34.087Z DEBUG dynamo_run::subprocess: 2025-06-06T19:02:34.087Z DEBUG decorators.cls_decorator_helper: Inferred dynamic dimensions for forward method of <class 'vllm.model_executor.models.llama.LlamaModel'>: ['input_ids', 'positions', 'intermediate_tensors', 'inputs_embeds']   
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess: 2025-06-06T19:02:34.249Z ERROR engine.run_mp_engine: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 47.36 GiB of which 112.44 MiB is free. Process 2585863 has 42.16 GiB memory in use. Process 2587244 has 1.79 GiB memory in use. Of the allocated memory 1.31 GiB is allocated by PyTorch, and 2.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess: Traceback (most recent call last):
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 586, in run_mp_engine
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     engine = MQLLMEngine.from_vllm_config(
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 248, in from_vllm_config
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     return cls(
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:            ^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 177, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.engine = LLMEngine(*args, **kwargs)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 307, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.model_executor = executor_class(vllm_config=vllm_config, )
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 52, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self._init_executor()
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.collective_rpc("load_model")
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     answer = run_method(self.driver_worker, method, args, kwargs)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/utils.py", line 2378, in run_method
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     return func(*args, **kwargs)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 200, in load_model
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.model_runner.load_model()
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1126, in load_model
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.model = get_model(vllm_config=self.vllm_config)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     return loader.load_model(vllm_config=vllm_config)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 452, in load_model
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     model = _initialize_model(vllm_config=vllm_config)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 133, in _initialize_model
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     return model_class(vllm_config=vllm_config, prefix=prefix)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 486, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.model = self._init_model(vllm_config=vllm_config,
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 527, in _init_model
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     return LlamaModel(vllm_config=vllm_config,
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/compilation/decorators.py", line 151, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 321, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.start_layer, self.end_layer, self.layers = make_layers(
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                                                     ^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 610, in make_layers
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 323, in <lambda>
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     lambda prefix: layer_type(config=config,
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 254, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.mlp = LlamaMLP(
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                ^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 78, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.down_proj = RowParallelLinear(
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                      ^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 1169, in __init__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     self.quant_method.create_weights(
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 178, in create_weights
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     weight = Parameter(torch.empty(sum(output_partition_sizes),
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/torch/utils/_device.py", line 104, in __torch_function__
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:     return func(*args, **kwargs)
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 47.36 GiB of which 112.44 MiB is free. Process 2585863 has 42.16 GiB memory in use. Process 2587244 has 1.79 GiB memory in use. Of the allocated memory 1.31 GiB is allocated by PyTorch, and 2.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)   
    2025-06-06T19:02:34.250Z DEBUG dynamo_run::subprocess: Process SpawnProcess-1:
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess: Traceback (most recent call last):
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.run()
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self._target(*self._args, **self._kwargs)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 600, in run_mp_engine
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     raise e
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 586, in run_mp_engine
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     engine = MQLLMEngine.from_vllm_config(
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 248, in from_vllm_config
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     return cls(
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:            ^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 177, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.engine = LLMEngine(*args, **kwargs)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 307, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.model_executor = executor_class(vllm_config=vllm_config, )
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 52, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self._init_executor()
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.collective_rpc("load_model")
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     answer = run_method(self.driver_worker, method, args, kwargs)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/utils.py", line 2378, in run_method
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     return func(*args, **kwargs)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 200, in load_model
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.model_runner.load_model()
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/worker/model_runner.py", line 1126, in load_model
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.model = get_model(vllm_config=self.vllm_config)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     return loader.load_model(vllm_config=vllm_config)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 452, in load_model
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     model = _initialize_model(vllm_config=vllm_config)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/model_loader/loader.py", line 133, in _initialize_model
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     return model_class(vllm_config=vllm_config, prefix=prefix)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 486, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.model = self._init_model(vllm_config=vllm_config,
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 527, in _init_model
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     return LlamaModel(vllm_config=vllm_config,
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/compilation/decorators.py", line 151, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 321, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.start_layer, self.end_layer, self.layers = make_layers(
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                                                     ^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 610, in make_layers
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 323, in <lambda>
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     lambda prefix: layer_type(config=config,
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 254, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.mlp = LlamaMLP(
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                ^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 78, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.down_proj = RowParallelLinear(
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                      ^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 1169, in __init__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     self.quant_method.create_weights(
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 178, in create_weights
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     weight = Parameter(torch.empty(sum(output_partition_sizes),
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/torch/utils/_device.py", line 104, in __torch_function__
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:     return func(*args, **kwargs)
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:34.252Z DEBUG dynamo_run::subprocess: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 47.36 GiB of which 112.44 MiB is free. Process 2585863 has 42.16 GiB memory in use. Process 2587244 has 1.79 GiB memory in use. Of the allocated memory 1.31 GiB is allocated by PyTorch, and 2.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
    2025-06-06T19:02:34.541Z DEBUG dynamo_run::subprocess: [rank0]:[W606 19:02:34.663896299 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
    2025-06-06T19:02:40.748Z DEBUG dynamo_run::subprocess: 2025-06-06T19:02:40.748Z DEBUG client.run_output_handler_loop: Shutting down MQLLMEngineClient output handler.   
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess: Traceback (most recent call last):
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:   File "/tmp/.tmpBzdG3l", line 295, in <module>
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:     asyncio.run(worker())
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:     return runner.run(main)
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    2025-06-06T19:02:40.750Z DEBUG dynamo_run::subprocess:     return self._loop.run_until_complete(task)
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/dynamo/runtime/__init__.py", line 41, in wrapper
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:     await func(runtime, *args, **kwargs)
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:   File "/tmp/.tmpBzdG3l", line 135, in worker
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:     await init(runtime, cmd_line_args())
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:   File "/tmp/.tmpBzdG3l", line 202, in init
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:     engine_client = await engine_context.__aenter__()
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:     return await anext(self.gen)
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:            ^^^^^^^^^^^^^^^^^^^^^
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:   File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 269, in build_async_engine_client_from_engine_args
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess:     raise RuntimeError(
    2025-06-06T19:02:40.751Z DEBUG dynamo_run::subprocess: RuntimeError: Engine process failed to start. See stack trace for the root cause.

</details>

<details>
<summary><b>Dynamo Debug Logs 2</b></summary>

    2025-06-06T19:57:40.419Z DEBUG dynamo_run::subprocess: 2025-06-06T19:57:40.419Z DEBUG client.run_metrics_loop: Metrics successful.   
    2025-06-06T19:57:40.419Z DEBUG dynamo_runtime::pipeline::network::tcp::server: issued control message Kill to sender
    2025-06-06T19:57:40.419Z DEBUG dynamo_run::subprocess: 2025-06-06T19:57:40.419Z ERROR dynamo_runtime::pipeline::network::tcp::client: failed to join writer task: I/O error: Broken pipe (os error 32)
    2025-06-06T19:57:40.419Z DEBUG dynamo_run::subprocess: 
    2025-06-06T19:57:40.419Z DEBUG dynamo_run::subprocess: Caused by:
    2025-06-06T19:57:40.419Z DEBUG dynamo_run::subprocess:     Broken pipe (os error 32)
    2025-06-06T19:57:40.438Z DEBUG dynamo_run::subprocess: 2025-06-06T19:57:40.437Z DEBUG scheduler.schedule: Assinged blocks: {19: [0, 7, 101, 102, 103]}   
    2025-06-06T19:57:40.439Z DEBUG dynamo_run::subprocess: 2025-06-06T19:57:40.439Z DEBUG client.run_metrics_loop: Metrics successful.   
    2025-06-06T19:57:40.439Z DEBUG dynamo_run::subprocess: 2025-06-06T19:57:40.439Z ERROR dynamo_runtime::pipeline::network::ingress::push_handler: Failed to publish response for stream b427ca7c-d08f-4392-949e-ee269e28a4ae

</details>

### Screenshots

Image

Image

### PR DESCRIPTION
**Pull request by alec-flowers**
#### Overview:

Fixes: https://github.com/ai-dynamo/dynamo/issues/1422

## Summary by CodeRabbit

- **Style**
  - Increased the visibility of subprocess output by logging stdout lines at the info level and stderr lines at the error level instead of debug.

### CODE REVIEW

**Review by rmccorm4 — APPROVED** [review]
This should unblock the people seeing silent issues from `out=<vllm|sglang|tensorrtllm>`

To avoid being too noisy, we'll probably want to augment/modify current usage of `strip_log_prefix` to instead detect log level keywords and log the corresponding level here.

For things that printing raw text and not using some structured logging, we can probably group stdout->info and stderr->error or something.

Will need to refine the noise level here I think, but not in this PR.

File: launch/dynamo-run/src/subprocess.rs [hunk 1]
```diff
@@ -92,13 +92,13 @@ pub async fn start(
...
         while let Ok(Some(line)) = lines.next_line().await {
-            tracing::debug!("{}", strip_log_prefix(&line));
+            tracing::info!("{}", strip_log_prefix(&line));
         }
     });
     tokio::spawn(async move {
         let mut lines = stderr.lines();
         while let Ok(Some(line)) = lines.next_line().await {
-            tracing::debug!("{}", strip_log_prefix(&line));
+            tracing::info!("{}", strip_log_prefix(&line));
```
Comment (rmccorm4) [inline launch/dynamo-run/src/subprocess.rs]: Based on Zicheng's output repro's CUDA OOM error (and original issue: https://github.com/ai-dynamo/dynamo/issues/1422) - I think we might want to `tracing::error!` for `stderr` for now - otherwise they blend into healthy info logs.

Comment (alec-flowers) [reply launch/dynamo-run/src/subprocess.rs]: Ah yes

**Comment by grahamking** [comment]
> instead detect log level keywords and log the corresponding level here.

I started with that, but unfortunately all these engines are not designed for interactive use, so their logs are quite noisy.  That's why I switched everything to debug. The expectation is most users run in info mode. `out=text` complicates things here, but it is most users first impression of dynamo so we have to get it right.

**Comment by alec-flowers** [comment]
> > instead detect log level keywords and log the corresponding level here.
> 
> I started with that, but unfortunately all these engines are not designed for interactive use, so their logs are quite noisy. That's why I switched everything to debug. The expectation is most users run in info mode. `out=text` complicates things here, but it is most users first impression of dynamo so we have to get it right.

Yea the problem was most users became confused when they didn't see anything happen. There has to be the right balance especially for what is shown at default.

If we decide to hide the logs then I think we need to at least display some form of working log or an explanation on how to see logs if they want.

**Comment by grahamking** [comment]
> Yea the problem was most users became confused when they didn't see anything happen. There has to be the right balance especially for what is shown at default.
> 
> If we decide to hide the logs then I think we need to at least display some form of working log or an explanation on how to see logs if they want.

Agreed. 

We might want to parse out the log level, show error as error and everything else as debug, and then some smart way to identify a stack trace. 

That might be as simple as looking for a line that starts with "Traceback" (without the normal datetime / log-level prefix) and logging everything from then onwards as an error.

**Comment by grahamking** [comment]
I *think* I also tried logging anything without a valid logging prefix as a warning, but that was also noisy. Log hygiene is an under-appreciated skill in software engineering.
