### PR TITLE
fix: guard KV-indexer against self-referential blocks

### LINKED ISSUE #4394: [BUG]: KV-Router indexer receives invalid self-referential blocks
### Describe the Bug

During startup (even before any client traffic), the KV Router indexer replays stored events and receives `Stored` payloads where `parent_hash == block_hash`. When such a self-referential block arrives, the indexer panics (RefCell already borrowed) and the frontend reports IndexerOffline for every request. 

### Steps to Reproduce

1. Launch the router + backend stack (sglang agg+router example for me) after wiping state.
2. Let the frontend replay discovery/JetStream logs; no user requests are needed.
3. Watch the router logs: 

Smth like this:
```
[2m2025-11-17T16:25:34.092833Z[0m [35mTRACE[0m [2mdynamo_llm::kv_router::indexer[0m[2m:[0m RadixTree::apply_event: Store operation: Stored(KvCacheStoreData { parent_hash: Some(ExternalSequenceBlockHash(1038227862389840939)), blocks: [KvCacheStoredBlockData { block_hash: ExternalSequenceBlockHash(14681692605194770420), tokens_hash: LocalBlockHash(10137791622231551288) }] }) [3mid[0m[2m=[0m20
[2m2025-11-17T16:25:34.092837Z[0m [35mTRACE[0m [2mdynamo_llm::kv_router::indexer[0m[2m:[0m RadixTree::apply_event: Store operation: Stored(KvCacheStoreData { parent_hash: Some(ExternalSequenceBlockHash(14681692605194770420)), blocks: [KvCacheStoredBlockData { block_hash: ExternalSequenceBlockHash(4876245085811370259), tokens_hash: LocalBlockHash(5370710679942703327) }] }) [3mid[0m[2m=[0m20
[2m2025-11-17T16:25:34.092863Z[0m [35mTRACE[0m [2mdynamo_llm::kv_router::indexer[0m[2m:[0m RadixTree::apply_event: Store operation: Stored(KvCacheStoreData { parent_hash: Some(ExternalSequenceBlockHash(4876245085811370259)), blocks: [KvCacheStoredBlockData { block_hash: ExternalSequenceBlockHash(301883270755155684), tokens_hash: LocalBlockHash(16694144929205133692) }] }) [3mid[0m[2m=[0m20
[2m2025-11-17T16:25:34.092876Z[0m [35mTRACE[0m [2mdynamo_llm::kv_router::indexer[0m[2m:[0m RadixTree::apply_event: Store operation: Stored(KvCacheStoreData { parent_hash: Some(ExternalSequenceBlockHash(301883270755155684)), blocks: [KvCacheStoredBlockData { block_hash: ExternalSequenceBlockHash(18111100450886515351), tokens_hash: LocalBlockHash(5311879336024216665) }] }) [3mid[0m[2m=[0m20
[2m2025-11-17T16:25:34.092883Z[0m [35mTRACE[0m [2mdynamo_llm::kv_router::indexer[0m[2m:[0m RadixTree::apply_event: Store operation: Stored(KvCacheStoreData { parent_hash: Some(ExternalSequenceBlockHash(18111100450886515351)), blocks: [KvCacheStoredBlockData { block_hash: ExternalSequenceBlockHash(18111100450886515351), tokens_hash: LocalBlockHash(5311879336024216665) }] }) [3mid[0m[2m=[0m20

thread '<unnamed>' panicked at /opt/dynamo/lib/llm/src/kv_router/indexer.rs:408:26:
RefCell already borrowed
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::cell::panic_already_borrowed::do_panic::runtime
   3: core::cell::panic_already_borrowed
   4: dynamo_llm::kv_router::indexer::RadixTree::apply_event
   5: dynamo_llm::kv_router::indexer::KvIndexer::new_with_frequency::{{closure}}::{{closure}}
   6: tokio::runtime::runtime::Runtime::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected Behavior

* KV indexer validates block sequences and never panics on malformed events.
* Frontend continues serving requests even if KV routing is temporarily unavailable.
* Upstream components never emit self-referential Stored events.

### Actual Behavior

* KV Indexer thread panicked on malformed event.
* Frontend response 500 on every request after that.
* Upstream components emit self-referential Stored events.

### Environment

* Dynamo from main (commit dce20d06bf82399f88e3e4b424559fc3cb548630)
* SGLang aggregated workers

### Additional Context

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by vladnosiv**
#### Overview:

* Add validation in `RadixTree::apply_event` to detect/skip `Stored` entries where `parent_hash == block_hash`, preventing the RefCell panic.
* Log the offending worker/block in best-effort mode so we can trace upstream producers of malformed events.

#### Related Issues: 

Partially Resolve: https://github.com/ai-dynamo/dynamo/issues/4394

## Summary by CodeRabbit

* **Bug Fixes**
  * Fixed an issue where invalid block structures could occur during data storage operations, preventing potential infinite loops and improving system stability.

### CODE REVIEW

**Comment by vladnosiv** [comment]
@PeaBrane here's a hotfix for https://github.com/ai-dynamo/dynamo/issues/4394

File: lib/llm/src/kv_router/indexer.rs [hunk 1]
```diff
@@ -380,7 +383,20 @@ impl RadixTree {
...
+                            worker_id = worker.worker_id.to_string(),
+                            dp_rank = worker.dp_rank,
+                            id,
+                            block_hash = ?block_id.block_hash,
+                            "Detected self-referential block insertion; skipping block"
+                        );
+                        return Err(KvCacheEventError::InvalidBlockSequence);
+                    }
+
                     let mut inner = current.borrow_mut();
```
Comment (PeaBrane) [inline lib/llm/src/kv_router/indexer.rs]: It may be cleaner/idiomatic to just do `try_borrow_mut()` here, and if error then we handle it as you did. Nicer to rely directly on Rust internals instead of manually checking

File: lib/llm/src/kv_router/indexer.rs
Comment (PeaBrane) [inline lib/llm/src/kv_router/indexer.rs]: It may be cleaner/idiomatic to just do try_borrow_mut() here, and if error then we handle it as you did. Nicer to rely directly on Rust internals instead of manually checking.

Edit: thinking more about this. You're approach checks against the parent hash of the chain, while my suggestion would check against the immediately parent. Neither would prevent a cycle in the chain.

Perhaps a way to guarantee that the entire chain does not contain a cycle is to not `drop(inner)`, so we don't release the `RefCell`s

Comment (vladnosiv) [reply lib/llm/src/kv_router/indexer.rs]: I tried to implement a loop check on blocks. Obviously, there is the simplest solution via HashSet, which is clear, readable, and simple. It is currently implemented in the branch.

With the option of checking for a cycle by the borrow checker, everything turned out to be not so simple. Any approaches with saving the guard stack on the fly did not pass one or the other checker check. The only way out I saw was to split everything into 2 passes. Here is the code: https://gist.github.com/vladnosiv/800382dc705af07087dd2cfb11524bb7

This solution is obviously fragile, complex, and difficult to read. I'm not an expert in Rust, maybe there are some simpler ways here. However, it does not seem to me non-ideomatic to explicitly check the validity of inputs that do not rely on the internals of Rust. It seems that this is quite ideomatic from the point of view of software development. Since in addition to such a check, other invariants may well be checked in the future and doing them separately before the actual operation of the Store operation looks like a good solution.

**Review by PeaBrane — APPROVED** [review]
