### PR TITLE
fix: Interactive inputs actually stops, does not ignore stop token

### LINKED ISSUE #2918: [BUG]: Interactive frontend cannot stop the output
### Describe the Bug

Interactive frontend cannot stop the output

### Steps to Reproduce

1. uv pip install ai-dynamo\[vllm\]==0.4.1
2. python -m dynamo.vllm --model deepseek-ai/DeepSeek-R1-Distill-Llama-8B
3. python -m dynamo.frontend --interactive
4. input anything

### Expected Behavior

The output should stop and wait for my second input.

### Actual Behavior

```
(dynamo-vllm) root@H20-GPU-19:~# python -m dynamo.frontend --interactive
2025-09-06T09:24:28.874789Z  INFO dynamo_llm::entrypoint::input::common: Waiting for remote model..
2025-09-06T09:24:30.050880Z  INFO dynamo_llm::discovery::watcher: added model model_name="deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
2025-09-06T09:24:30.050930Z  INFO dynamo_llm::entrypoint::input::common: Connected to deepseek-ai/DeepSeek-R1-Distill-Llama-8B
2025-09-06T09:24:30.050958Z  INFO dynamo_llm::entrypoint::input::text: Ctrl-c to exit
✔ User · hi
Alright, the user just said "hi." That's pretty straightforward. I should respond in a friendly and welcoming manner.

I want to make sure they feel comfortable asking for help, so I'll keep it open-ended.

Maybe I can offer assistance without being too pushy.

I should probably mention the different ways they can ask for help, like with questions or specific topics.

Let me keep it simple and conversational.

Yeah, something like, "Hello! How can I assist you today?" should work nicely.

Hello! How can I assist you today? Whether you have a question, need advice, or just want to chat, I'm here to help. Let me know what's on your mind! 😊

Hello! How can I assist you today? Whether you have a question, need advice, or just want to chat, I'm here to help. Let me know what's on your mind! 😊

(Or, if you prefer a different approach, feel free to ask!) 😊

If you have any specific questions or need information on a particular topic, feel free to ask, and I'll do my best to help you out! 😊

Example of how to continue the conversation:

You: "hi"

Me: "Hello! How can I assist you today?"

You: "I need help with something."

Me: "Of course! What would you like to know or discuss?"

You: "I'm not sure where to start."

Me: "That's okay! Let me know what you're thinking about, and I'll do my best to guide you."

You: "Okay, I have a question about..."

Me: "Sure, I'd be happy to help! What would you like to know about [topic]?"

And so on... 😊

I'm here to help! Just let me know what you need. 😊

(If you'd like a more structured or step-by-step approach, let me know, and I can adjust accordingly! 😊)

So, go ahead and share what you need help with, and I'll be here to assist you! 😊

……
……
……
cannot stop
```

### Environment

I used a new uv venv and installed dynamo by

```
uv pip install ai-dynamo[vllm]==0.4.1
```

My driver version is 550.127.08.
GPU is H20-3e.

### Additional Context

*No response*

### Screenshots

*No response*

### PR DESCRIPTION
**Pull request by grahamking**
Closes #2918

Removes the `echo_core` engine which relied on ignoring stop tokens, so that we only have a single `echo` engine. That's easier to explain.

`echo_core` would have been useful for debugging template issues but in practice a `tracing::debug!` statement is just as useful and simpler to use.

## Summary by CodeRabbit

- Refactor
  - Consolidated echo engines into a single “echo” engine for simpler selection. Existing “echo_full” inputs remain compatible as an alias. Engine listings now show only “echo.”
- Documentation
  - Updated guides and examples to use “echo” throughout.
  - Clarified Echo configuration, including DYN_TOKEN_ECHO_DELAY_MS (default ~10ms/token ≈100 tokens/s).
  - Removed obsolete examples and options related to the previous split (e.g., ignore_eos).

### CODE REVIEW

File: lib/runtime/src/system_status_server.rs [hunk 1]
```diff
@@ -444,21 +444,27 @@ mod integration_tests {
...
                 // Prepare test cases
                 let mut test_cases = vec![];
-                if custom_health_path.is_none() {
-                    // When using default paths, test the default paths
-                    test_cases.push(("/health", expected_status, expected_body));
-                } else {
-                    // When using custom paths, default paths should not exist
-                    test_cases.push(("/health", 404, "Route not found"));
-                    test_cases.push((custom_health_path.unwrap(), expected_status, expected_body));
+                match custom_health_path {
```
Comment (rmccorm4) [inline lib/runtime/src/system_status_server.rs:447]: is this just an unrelated cleanup from if -> match?

**Review by rmccorm4 — APPROVED** [review]

File: lib/runtime/src/system_status_server.rs (hunk 1 above)
Comment (grahamking) [reply lib/runtime/src/system_status_server.rs:447]: Yes, clippy caught it. I had to do `cargo clippy --features integration --tests`, which I guess I never did before and our CI doesn't.
