### PR TITLE
fix: Fix race condition in kv_router unit test

### LINKED ISSUE #1132: [BUG]: race condition in kv router unit tests
### Describe the Bug

The `test_frequency` test will occasionally fail.  It's likely there need to be some fencing operation to ensure that the event has been applied.

### Steps to Reproduce

I'll update this with examples from CI where it will fail and when re-run, it will pass.

### Expected Behavior

Test never fails.

### Actual Behavior

Test will fail intermittently

### Environment

```
cd lib/llm
cargo test
```

### Additional Context

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by grahamking**
Removed the hard coded sleeps, explained what we're testing.

Closes https://github.com/ai-dynamo/dynamo/issues/1132

The race condition is that `apply_event` sends a message on a channel, it does not directly apply the event. At some later point the tokio runtime schedules the task running the channel receiver, which applies the event. If that had not happened yet the test would fail.

### CODE REVIEW

**Review by rmccorm4 — APPROVED** [review]

File: lib/llm/src/kv_router/indexer.rs [hunk 1]
```diff
@@ -1304,65 +1318,107 @@ mod tests {
     #[tokio::test]
     #[apply(indexer_template)]
     async fn test_frequency(num_shards: usize, kv_block_size: usize) {
+        const ONE_MILLIS: Duration = Duration::from_millis(1);
```
Comment (rmccorm4) [inline lib/llm/src/kv_router/indexer.rs:1321]: Any significance for giving a const to 1ms, but not to the other usages, ex: 50ms, 10ms, etc. used as Duration::from_millis(50) below?

File: lib/llm/src/kv_router/indexer.rs [hunk 2]
```diff
@@ -1304,65 +1318,107 @@ mod tests {
...
+        assert_eq!(overlap.scores.len(), 1, "Still one worker matches");
+        assert_eq!(
+            overlap.frequencies,
+            vec![1, 1, 1, 1],
+            "We should see the first access now"
+        );
 
-        time::sleep(Duration::from_millis(100)).await;
+        // Let those two accesses expire
+        time::sleep(expiration + Duration::from_millis(10)).await;
```
Comment (rmccorm4) [inline lib/llm/src/kv_router/indexer.rs:1393]: Would something like expiration+timeout here be clearer? Assuming the + 10ms here is to match timeout

Comment (rmccorm4) [reply lib/llm/src/kv_router/indexer.rs:1393]: On second read, maybe this is just sleeping for expiration + some number to increase consistency?  Wasn't immediately clear of the importance of +10ms specifically vs. any other number at a glance

File: lib/llm/src/kv_router/indexer.rs (hunk 1 above)
Comment (grahamking) [reply lib/llm/src/kv_router/indexer.rs:1321]: It's used multiple times, inside the wait loop. That's the only reason.

File: lib/llm/src/kv_router/indexer.rs (hunk 2 above)
Comment (grahamking) [reply lib/llm/src/kv_router/indexer.rs:1393]: The 10ms is any value to put us beyond the expiration. 1ms would have sufficed. It's expiration + "a bit".

**Comment by rmccorm4** [comment]
Do you mind adding a quick summary of the race condition specific fix in the PR description?
