### PR TITLE
fix: deepseek tool parsing fixed

### LINKED ISSUE #3599: [BUG]: `tool_call_end` is not handled for DeepSeek V3.1 parser
### Describe the Bug

DeepSeek V3.1's tool call tokens looks like this:
```
<｜tool▁calls▁begin｜><｜tool▁call▁begin｜>TodoWrite<｜tool▁sep｜>{"todos":
[{"content": "Explore the root directory structure", "status": "in_progress", "activeForm":
   "Exploring the root directory structure"}, {"content": "Examine package.json and
  configuration files", "status": "pending", "activeForm": "Examining package.json and
  configuration files"}, {"content": "Analyze source code structure and key modules",
  "status": "pending", "activeForm": "Analyzing source code structure and key modules"},
  {"content": "Identify main entry points and architectural patterns", "status": "pending",
  "activeForm": "Identifying main entry points and architectural patterns"}, {"content":
  "Summarize the codebase purpose and functionality", "status": "pending", "activeForm":
  "Summarizing the codebase purpose and
  functionality"}]}<｜tool▁call▁end｜><｜tool▁calls▁end｜>
```

However, in [the current implementation](https://github.com/ai-dynamo/dynamo/blob/cd2389baefa20c4152d0e7859dc06fdad8abced5/lib/parsers/src/tool_calling/config.rs#L158), it looks like it only parses `<｜tool▁calls▁end｜>`, and not `<｜tool▁call▁end｜>`, making parsing fail.

### Steps to Reproduce

1. Using vLLM as the backend, run [`DeepSeek-V3.1`](https://huggingface.co/deepseek-ai/DeepSeek-V3.1) (or [`DeepSeek-V3.1-Terminus`](https://huggingface.co/deepseek-ai/DeepSeek-V3.1-Terminus))
2. Make a OpenAI-compatible request with tools
3. See the raw output

### Expected Behavior

Tool tokens parsed correctly, with no random `<｜tool▁calls▁end｜>` or `<｜tool▁call▁end｜>` in the output if the client is supporting tools correctly.

### Actual Behavior

Tool tokens are not parsed correctly.

### Environment

OS: Ubuntu 22.04.5 LTS
Kernel: 5.15.0-126-generic
CPU: Dual Intel Xeon Platinum 8460Y+ / 80 cores
GPUs: NVIDIA H200 x8
CUDA: 12.8.1
Python: 3.12.3
ai-dynamo: 0.5.0

### Additional Context

I've been discussing with more context on [Discord](https://discord.com/channels/1351250028588437504/1351301865039724605/1426118876130709544).

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by elyasmnvidian**
Fixes: https://github.com/ai-dynamo/dynamo/issues/3599

## Summary

This PR fixes critical issues with the DeepSeek tool call parser for streaming JSON responses and adds comprehensive integration testing infrastructure.

### Key Changes

- **Fixed DeepSeek tool call parser** to correctly handle streaming JSON responses
- **Added parallel tool call integration tests** to validate multi-tool scenarios
- **Enhanced tool calling configuration** for improved parser integration
- **Created helper tooling** for generating and capturing tool call stream test data

## Problem Statement

The DeepSeek tool call parser was failing to correctly parse streaming JSON responses, particularly when handling tool calls with complex arguments. The parser underwent several iterations to handle edge cases in the streaming format, requiring significant refactoring of the JSON parsing logic.

### 1. DeepSeek Parser Refactoring (`lib/parsers/src/tool_calling/json/deepseek_parser.rs`)
- **328 lines modified** with significant refactoring of the JSON parsing logic
- Improved handling of streaming JSON chunks
- Fixed edge cases in tool call argument parsing
- Enhanced state management during streaming
- Now correctly handles incomplete JSON chunks during streaming
- Manages state transitions between reasoning and tool call content
- Parses tool call arguments that arrive fragmented across multiple chunks
- Distinguishes between regular content and structured tool calls

### 2. Configuration Updates (`lib/parsers/src/tool_calling/config.rs`)
- **28 lines modified** for better integration with updated parser
- Adjusted tool calling configuration to support improved parsing

### 3. Parallel Tool Call Integration Tests (`lib/llm/tests/parallel_tool_call_integration.rs`)
- **New 96-line integration test suite** for parallel tool calls
- Validates multi-tool call scenarios
- Ensures parser correctly handles concurrent tool invocations

### 4. Helper Tooling (`lib/llm/tests/scripts/tool_call_stream_request_helper.py`)
- **167-line Python script** for generating and capturing streaming test data
- Enables easy creation of new test cases from live SGLang endpoints
- Facilitates regression testing with real-world data

## Testing

The changes have been validated with:
- Integration tests for parallel tool calls
- Manual testing with streaming endpoints
- Validation against real SGLang responses

## Implementation Details

The parser now correctly:
- Handles incomplete JSON chunks during streaming
- Manages state transitions between reasoning and tool call content
- Parses tool call arguments that arrive fragmented across multiple chunks
- Distinguishes between regular content and structured tool calls

## Summary by CodeRabbit

* New Features
  * Expanded tool-call parsing compatibility for DeepSeek v3.1, recognizing more start/end/separator tokens.
* Bug Fixes
  * More robust extraction of normal content and parsing of multiline or imperfect JSON in tool calls.
* Refactor
  * Reworked parser to token-based extraction for improved reliability across formats.
* Tests
  * Added comprehensive streaming fixtures and end-to-end cases covering tool and no-tool scenarios across multiple models.
* Chores
  * Introduced a lightweight CLI helper to issue streaming requests and summarize chunk counts.

### CODE REVIEW

File: lib/parsers/src/tool_calling/config.rs [hunk 1]
```diff
@@ -154,8 +159,29 @@ impl ToolCallConfig {
...
+                    "<｜tool_calls_end｜>".to_string(),
+                    "<｜tool_call_end｜>".to_string(),
+                    "<|tool_calls_end|>".to_string(),
+                    "<|tool_call_end|>".to_string(),
+                ],
+                tool_call_separator_tokens: vec![
+                    "<｜tool▁sep｜>".to_string(),
+                    "<|tool▁sep|>".to_string(),
+                    "<｜tool_sep｜>".to_string(),
+                    "<|tool_sep|>".to_string(),
```
Comment (ayushag-nv) [inline lib/parsers/src/tool_calling/config.rs]: @elyasmnvidian Why so many combination ? There should be one combination that should work right ?

**Review by ayushag-nv — CHANGES_REQUESTED** [review]

File: lib/parsers/src/tool_calling/config.rs (hunk 1 above)
Comment (elyasmnvidian) [reply lib/parsers/src/tool_calling/config.rs]: just to be safe, IF the _ and | get converted somehow the tool calling will still work (big IF, and this model is hard to run so lets play it safe). Removing it has no benefit? Also I think it illustrates to anyone who wants to contribute that its clear there are special characters and they need to be aware of that.

**Review by ayushag-nv — APPROVED** [review]
Looks Good
