### PR TITLE
fix: tool_choice=required bypasses format-specific parsers (#6821)

### LINKED ISSUE #6821: tool_choice: required causes tool call to always leak as raw XML (never parsed)
## Summary

When `tool_choice: "required"` is set in a `/v1/responses` or `/v1/chat/completions` request, the `qwen3_coder` tool call parser **never** extracts the tool call as a structured `function_call` item. The tool call is always returned as raw `<tool_call>` XML in the `output_text` content.

## Reproduction

**Model**: `nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8`
**Parser**: `--dyn-tool-call-parser qwen3_coder`
**Backend**: TRT-LLM (pytorch)

```bash
curl -X POST "$ENDPOINT/v1/responses" \
  -H "Content-Type: application/json" \
  -d '{
    "model": "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8",
    "input": "What is the weather in Paris?",
    "tools": [
      {"type":"function","name":"get_weather","description":"Get the current weather for a given location","parameters":{"type":"object","properties":{"location":{"type":"string"}},"required":["location"]}}
    ],
    "tool_choice": "required",
    "stream": false,
    "max_output_tokens": 300,
    "temperature": 0.0
  }'
```

## Observed behavior

Tested 5 times — **100% failure rate**. The tool call is never parsed:

```
Run 1: reasoning + LEAKED raw XML
Run 2: reasoning + LEAKED raw XML
Run 3: reasoning + LEAKED raw XML
Run 4: reasoning + LEAKED raw XML
Run 5: reasoning + LEAKED raw XML
```

Output contains:
```json
{
  "type": "message",
  "content": [{
    "type": "output_text",
    "text": "\n<tool_call>\n<function=get_weather>\n<parameter=location>\nParis\n</parameter>\n</function>\n</tool_call>\n"
  }]
}
```

Note: the same request with `tool_choice: "auto"` (or omitted) **does** parse the tool call correctly into a structured `function_call` item. The issue is specific to `tool_choice: "required"`.

## Expected behavior

The tool call should be extracted as a structured `function_call` output item:
```json
{"type": "function_call", "name": "get_weather", "arguments": "{\"location\":\"Paris\"}", "call_id": "...", "status": "completed"}
```

## Impact

Any agentic workflow using `tool_choice: "required"` to force tool invocation will receive raw XML instead of structured tool calls, breaking tool dispatch logic.

## Environment

- Dynamo container: `nvcr.io/nvidian/dynamo-dev/tensorrtllm-runtime:vvagias-responses-api-v6`
- Also reproduced on `inference-api.nvidia.com` with model `nvidia_dynamo/nvidia/nvidia-nemotron-3-nano-30b-a3b`

### PR DESCRIPTION
**Pull request by AsadShahid04**
## Problem

When `tool_choice` is set to `"required"` or a named function in a `/v1/chat/completions` or `/v1/responses` request, models that use non-JSON tool call formats (qwen3_coder XML, pythonic, harmony, DSML, etc.) have their tool calls **silently ignored**. The raw markup leaks into `output_text` instead of being parsed into structured `function_call` items. This is a 100% failure rate for affected parsers under `tool_choice=required`.

`tool_choice: "auto"` works correctly because it follows a different code path that sets the `tool_call_parser`.

## Root Cause

In `lib/llm/src/preprocessor.rs::apply_tool_calling_jail()`, the match on `tool_choice` unconditionally activates **Immediate JSON jail mode** via `tool_choice_required()` / `tool_choice_named()` on the builder, WITHOUT also setting the `tool_call_parser`. The Immediate mode only understands raw JSON (`{...}` or `[{...}]`), so any model emitting a non-JSON format (XML `<tool_call>...</tool_call>`, pythonic, etc.) has its output silently dropped.

## Fix

When a `tool_call_parser` is configured, always use **marker-based jail mode** regardless of the `tool_choice` value. This ensures the format-specific parser is invoked to detect and extract tool calls correctly. Immediate JSON mode is preserved as a fallback for `required`/`named` when **no parser is configured** (the model is expected to emit raw JSON in that case).

**Files changed:**
- `lib/llm/src/preprocessor.rs` — Prioritize marker-based parser over Immediate JSON mode when a parser is configured
- `lib/llm/tests/test_jail.rs` — Added regression test `test_tool_choice_required_with_qwen3_coder_parser`

## Affected Parsers

qwen3_coder, nemotron_nano, pythonic, harmony, dsml, glm47, kimi_k2, and any future non-JSON parser.

## Testing

- Added regression test covering `tool_choice=required` with qwen3_coder parser
- Existing `tool_choice` tests for JSON-only (no parser) paths pass unchanged
- Manually verified that `tool_choice=auto` behavior is unaffected

Fixes #6821

## Summary by CodeRabbit

* **New Features**
  * Tool calling now supports format-specific parsers (e.g., XML-based parsers) alongside JSON-based parsing.

* **Bug Fixes**
  * Fixed tool-calling configuration to conditionally apply appropriate parsing modes based on parser availability.

* **Tests**
  * Added regression test coverage for XML-based tool parsing with required tool-choice behavior.

### CODE REVIEW

**Comment by dagil-nvidia** [comment]
/ok to test [9888ada](https://github.com/ai-dynamo/dynamo/pull/7589/commits/9888ada8e82f30a83200c8e820647735d5747c3e)

**Comment by grahamking** [comment]
@AsadShahid04 can you fix the clippy errors? `rust-clippy` check.

**Comment by vvagias** [comment]
Rebased onto main and fixed CI (clippy lint + struct wrapper change).

**Comment by rmccorm4** [comment]
/ok to test [961d6c4](https://github.com/ai-dynamo/dynamo/pull/7589/commits/961d6c400726fdf1eed6a82aed48c3b4ad46e2e6)

File: lib/llm/src/protocols/openai/chat_completions/jail.rs [hunk 1]
```diff
@@ -856,6 +860,37 @@ impl JailedStream {
...
+                    } else {
+                        tool_calls
+                    };
+
+                    if tool_calls.is_empty() {
+                        // All parsed calls were for the wrong tool — return content choice
+                        return create_choice_stream(
+                            choice_index,
+                            Some(Role::Assistant),
+                            accumulated_content,
```
Comment (MatejKosec) [inline lib/llm/src/protocols/openai/chat_completions/jail.rs:886]: When all parsed tool calls get filtered out (model emitted the wrong tool name), `accumulated_content` here is the raw text between markers — i.e. the unparsed XML/pythonic markup. Returning it as content leaks the exact same markup this PR is fixing for the happy path.

Suggestion: return empty content (`""`) instead of `accumulated_content` here. The model disobeyed the `tool_choice=named` contract, so there's no useful content to surface — and leaking `<tool_call>...</tool_call>` XML into the response would confuse consumers.

```suggestion
                            "",
```

File: lib/llm/src/protocols/openai/chat_completions/jail.rs [hunk 2]
```diff
@@ -1004,6 +1039,7 @@ impl JailedStream {
     fn fix_finish_reason<S>(
         input_stream: S,
         jail_mode: JailMode,
+        named_tool_active: bool,
```
Comment (MatejKosec) [inline lib/llm/src/protocols/openai/chat_completions/jail.rs:1042]: nit: `named_tool_active` reads like "a named tool was invoked" when it actually means "the request specified `tool_choice=named`". Something like `is_named_tool_choice` or `tool_choice_is_named` would be clearer about intent.

File: lib/llm/tests/test_jail.rs [hunk 3]
```diff
@@ -3080,4 +3082,88 @@ mod parallel_jail_tests {
...
+                            !text.contains("<tool_call>"),
+                            "Raw XML should not leak as content, got: {}",
+                            text
+                        );
+                    }
+                }
+            }
+        }
+    }
 }
```
Comment (MatejKosec) [inline lib/llm/tests/test_jail.rs:3272]: nit: This test covers `Required` through the preprocessor — nice. Consider adding a companion test that calls `apply_tool_calling_jail` with `Some(ChatCompletionToolChoiceOption::Named(..))` + a parser, to exercise the preprocessor branch that wires up `named_tool_filter`. The `tool_choice.rs` tests cover the filter in isolation via `JailedStream::builder()`, but don't go through the preprocessor decision logic.

**Review by MatejKosec — APPROVED** [review]
Nice fix — the root cause analysis is spot-on and the approach (marker-based when parser is configured, immediate JSON as fallback) is clean. The `named_tool_filter` addition correctly preserves the `tool_choice=named` contract through the parser path.

One thing to address before merge: the markup leak when the filter drops all calls. A couple of nits inline as well.

**Review by rmccorm4 — APPROVED** [review]
LGTM other than Matej's comments

File: lib/llm/src/protocols/openai/chat_completions/jail.rs (hunk 1 above)
Comment (AsadShahid04) [reply lib/llm/src/protocols/openai/chat_completions/jail.rs:886]: Changed  to  on line 886 to return an empty string when the filter drops all tool calls. This prevents unparsed XML/markup from leaking into the response.

File: lib/llm/src/protocols/openai/chat_completions/jail.rs (hunk 2 above)
Comment (AsadShahid04) [reply lib/llm/src/protocols/openai/chat_completions/jail.rs:1042]: Renamed `named_tool_active` to `is_named_tool_choice` throughout the `fix_finish_reason` function. This better reflects that the variable means 'request specified tool_choice=named', not 'tool was invoked'.

File: lib/llm/tests/test_jail.rs (hunk 3 above)
Comment (AsadShahid04) [reply lib/llm/tests/test_jail.rs:3272]: Added `test_tool_choice_named_with_qwen3_coder_parser` in the parallel_jail_tests module. This test calls `apply_tool_calling_jail` with `Some(ChatCompletionToolChoiceOption::Named("get_weather".to_string()))` and a qwen3_coder parser, exercising the named_tool_filter preprocessing decision logic and verifying that finish_reason stays as Stop (not ToolCalls) for named tool choice.

**Comment by ishandhanani** [comment]
Fix lint please.

**Comment by huitianbai** [comment]
> Fix lint please.

@ishandhanani @rmccorm4 Hi, I also encountered the same issue, and this PR seems not to filter function tools when tool_choice is "named“ function. I referred to sglang implementation (https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/entrypoints/openai/serving_chat.py#L345).
And dynamo's logic: https://github.com/ai-dynamo/dynamo/blob/main/lib/llm/src/preprocessor/prompt/template/oai.rs#L425, it only emits all when tool choice is none. This will affect formatted prompt when tool choice is named function.

And I make a draft PR, maybe merge together https://github.com/ai-dynamo/dynamo/pull/7808

**Comment by vladnosiv** [comment]
Hi, I noticed this PR. Since I wrtied tool_choice support in december (https://github.com/ai-dynamo/dynamo/pull/4722), I'm wondering what problem we're actually facing. In fact, what immediate JSON mode is using for all models is the intended behavior. Since it seems this is the only way to **guarantee** a tool call (except for structural tag for xgrammar). 
This is achieved by passing through the guided decoding JSON schema generated for the tools. If the model does not generate JSON in this case, it means that there was no real forcing of the JSON schema. 
For example, SGLang + Dynamo still doesn't seem to forcing json schema, here's a relevant PR from us: https://github.com/ai-dynamo/dynamo/pull/6620

I didn't really understand how, after this PR, the tool call guarantee assumed for required/named modes is achieved.

**Comment by MatejKosec** [comment]
> Hi, I noticed this PR. Since I wrtied tool_choice support in december (#4722), I'm wondering what problem we're actually facing. In fact, what immediate JSON mode is using for all models is the intended behavior. Since it seems this is the only way to **guarantee** a tool call (except for structural tag for xgrammar). This is achieved by passing through the guided decoding JSON schema generated for the tools. If the model does not generate JSON in this case, it means that there was no real forcing of the JSON schema. For example, SGLang + Dynamo still doesn't seem to forcing json schema, here's a relevant PR from us: #6620
> 
> I didn't really understand how, after this PR, the tool call guarantee assumed for required/named modes is achieved.

Hey Vlad,  good to have the perspective of someone who built the original tool_choice support. You're right that true enforcement needs guided decoding wired through to the engine, which is what your PR #6620 was working toward. 

Without it, the JSON mode before this PR doesn't actually guarantee a tool call since it is post-generation parsing — the model still generates freely, the jail just tries to interpret the output as JSON from token 1. There's no grammar constraint forcing the model to produce valid JSON. So the "guarantee" was already best-effort, while breaking 100% of the time for models that don't emit raw JSON (qwen3_coder, pythonic, harmony, etc.).

The other thing to consider is reasoning models, and how they have evolved over the past 6 to 12 months. Qwen3, DeepSeek-R1, GLM-5 all emit thinking tokens before their tool calls. Even a JSON-format model produces something like:
```
  <think>The user wants weather in Paris, I should call get_weather.</think>
  [{"name": "get_weather", "arguments": {"location": "Paris"}}]
```
The immediate JSON mode starts parsing from token 1 — it sees <think> and fails because < isn't valid JSON. The actual tool call JSON is there, but the thinking prefix kills it. For non-JSON models like qwen3_coder the tool call itself is XML:
```
  <think>...</think>
  <tool_call>{"name": "get_weather", "arguments": {"location": "Paris"}}</tool_call>
```

The fix keeps Immediate JSON as the fallback when no parser is configured (simple JSON-only models that
don't think), and uses marker-based parsing when a parser is set. Both paths were already best-effort —
the difference is the marker-based path works across formats and improves compatibility with latest reasoning models.
