### PR TITLE
fix: etcd.rs - linear increasing watch with number of requests

### LINKED ISSUE #971: [BUG]: incremental etcd live watch never cleared.
### Describe the Bug

Each request creates a new etcd live watch
- even for the same 
- the etcd

-> system process 50k requests -> 50k live requests.

Image

Sending 1 request every ~10 seconds.

```
repro:
ENDPOINT=${1:-http://127.0.0.1:2379}
INTERVAL=${2:-5}

while true; do
  TS=$(date +"%Y-%m-%d %H:%M:%S")

  # 1) live v3 watch streams
  MVCC=$(curl -s "${ENDPOINT}/metrics" \
    | grep '^etcd_debugging_mvcc_watch_stream_total ' \
    | awk '{print $2}')
  
  # 2) v3 slow watchers (back-pressured streams)
  SLOW=$(curl -s "${ENDPOINT}/metrics" \
    | grep '^etcd_debugging_mvcc_slow_watcher_total ' \
    | awk '{print $2}')
  
  # 3) raw TCP/GRPC connections to port 2379
  CONNS=$(ss -Htn state established '( dport = :2379 )' | wc -l)

  printf "%s  live_watches=%s  slow_watches=%s  tcp_conns=%s\n" \
    "$TS" "${MVCC:-N/A}" "${SLOW:-N/A}" "${CONNS:-N/A}"

  sleep "$INTERVAL"
done
```

```
2025-05-07 02:01:04  live_watches=440  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:09  live_watches=441  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:14  live_watches=441  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:19  live_watches=442  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:24  live_watches=442  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:30  live_watches=442  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:35  live_watches=443  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:40  live_watches=443  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:45  live_watches=444  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:50  live_watches=444  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:01:55  live_watches=444  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:02:00  live_watches=445  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:02:05  live_watches=445  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:02:10  live_watches=446  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:02:15  live_watches=446  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:02:20  live_watches=446  slow_watches=0  tcp_conns=0
./bin/scrape_etcd.sh: line 33: ss: command not found
2025-05-07 02:02:25  live_watches=447  slow_watches=0  tcp_conns=0
```

### Steps to Reproduce

The core issue is in `pub async fn kv_get_and_watch_prefix(`, which creates a new watch stream. 
The tokio task that pushes into the channel never gets 
- shared among subscribers
- notified when subscriber disconnects (advanced)

### Expected Behavior

Not make etcd go OOM

### Actual Behavior

etcd goes OOM

### Environment

-

### Additional Context

- apply this diff for a fix: https://github.com/basetenlabs/dynamo/pull/17/commits/00ca608d67efec84326a78b293690413b875e1de 

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by PeaBrane**
#### Overview:

Cherry picked from
https://github.com/ai-dynamo/dynamo/pull/974

Copied description:
> Contribution by https://github.com/basetenlabs.
> Closes https://github.com/ai-dynamo/dynamo/issues/971
>
> Summary:
> - if no update on etcd watch is happening, watchers never notice that their downstream consumers (mspc channel rx) dropped
> - every request will create a new watcher
> - 500k requests without changing etcd -> high memory usage of etcd
>
> Is a "edge case" but not scaling your cluster during 500k requests might be typical (e.g. low / max capacity load).

### CODE REVIEW

File: lib/runtime/src/transports/etcd.rs [hunk 1]
```diff
@@ -340,39 +340,60 @@ impl Client {
         let kvs = get_response.take_kvs();
         tracing::trace!("initial kv count: {:?}", kvs.len());
 
-        let (tx, rx) = mpsc::channel(32);
+        let (tx, rx) = mpsc::channel(2048);
```
Comment (rmccorm4) [inline lib/runtime/src/transports/etcd.rs]: Did you find this buffer being a bottleneck? @michaelfeil

File: lib/runtime/src/transports/etcd.rs [hunk 2]
```diff
@@ -340,39 +340,60 @@ impl Client {
...
-                                    break;
-                                }
+                            // the stream ended or errored out
+                            _ => {
+                                tracing::info!("kv watch stream closed");
+                                return;
                             }
                         }
                     }
+                    _ = ticker.tick() => {
```
Comment (ryanolson) [inline lib/runtime/src/transports/etcd.rs]: I think you can just tax.closed().await here. 

No need for an interval.

**Review by ryanolson — CHANGES_REQUESTED** [review]

File: lib/runtime/src/transports/etcd.rs (hunk 2 above)
Comment (PeaBrane) [reply lib/runtime/src/transports/etcd.rs]: @ryanolson something like this?

File: lib/runtime/src/transports/etcd.rs [hunk 3]
```diff
@@ -340,39 +340,56 @@ impl Client {
...
+                tokio::select! {
+                    maybe_resp = watch_stream.next() => {
+                        match maybe_resp {
+                            Some(Ok(response)) => {
+                                for event in response.events() {
+                                    match event.event_type() {
+                                        etcd_client::EventType::Put => {
+                                            if let Some(kv) = event.kv() {
+                                                if let Err(err) = tx.send(WatchEvent::Put(kv.clone())).await {
+                                                    tracing::error!(
```
Comment (grahamking) [inline lib/runtime/src/transports/etcd.rs]: Is there anything you can do about the amount of indentation here?

File: lib/runtime/src/transports/etcd.rs (hunk 1 above)
Comment (grahamking) [reply lib/runtime/src/transports/etcd.rs]: I agree with @rmccorm4 . Often increasing the buffer just makes us hit whatever the root cause is, later. Why is it filling up?

File: lib/runtime/src/transports/etcd.rs
Comment (rmccorm4) [inline lib/runtime/src/transports/etcd.rs:1]: Do you have some kind of test to confirm the before/after behavior? ex:

> if no update on etcd watch is happening, watchers never notice that their downstream consumers (mspc channel rx) dropped

Is it easy to test this to catch a future regression?

> every request will create a new watcher

Do we have a simple test for the expectations here? Something like tracking number of watchers vs. expectations? Long term we should probably have some memory growth tests/checks, but those can be a bit tricky to get right without being flaky.

File: lib/runtime/src/transports/etcd.rs (hunk 1 above)
Comment (ryanolson) [reply lib/runtime/src/transports/etcd.rs]: Keep at 32. This should be the problem. 

Update: "should NOT be the problem" .... missed a critical word in my old comment...

Comment (rmccorm4) [reply lib/runtime/src/transports/etcd.rs]: > this should be the problem 

What was the problem caused by this change?

Comment (PeaBrane) [reply lib/runtime/src/transports/etcd.rs]: > > this should be the problem
> 
> What was the problem caused by this change?

Typo "shouldn't" i guess

**Review by ryanolson — APPROVED** [review]
