### PR TITLE
fix: prevent deadlock in etcd when flushing initial keys

### LINKED ISSUE #5079: [BUG]: Creating a Client hangs forever with 33+ instances
### Describe the Bug

If you create a dynamo client and there are already 33+ instances for that service, the create client call will block forever.

This is because `watch_internal` uses a channel with size 32...
https://github.com/ai-dynamo/dynamo/blob/9a3212b802a95d3612e860815a1e97fac7b94d24/lib/runtime/src/transports/etcd.rs#L351

and synchronously pushes all of the existing keys/values from etcd onto the channel before handing off the `rx` side of the channel for reading. Since nothing is reading from the channel, the 33rd send operation blocks forever:
https://github.com/ai-dynamo/dynamo/blob/9a3212b802a95d3612e860815a1e97fac7b94d24/lib/runtime/src/transports/etcd.rs#L410-L416

### Steps to Reproduce

1. Start a Dynamo deployment with 33 workers
2. Try to start another service that calls the following:
```
self.worker_client = (
    await runtime.namespace(namespace)
        .component(worker_component_name)
        .endpoint("generate")
        .client()
)
```

### Expected Behavior

Creating a client should succeed and the code should continue executing.

### Actual Behavior

That call will hang forever.

### Environment

This is on a CPU node (running the frontend). It's running Python 3.12 and `platform.platform()` is `Linux-5.15.0-1048-gke-x86_64-with-glibc2.39`.

We hit this issue on Dynamo 0.6.1 but the issue still exists on main and the links above are all to main.

### Additional Context

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by mohammedabdulwahhab**
#### Overview:

Fixes #5079 

- Channel size is dynamically allocated to be atleast as big as the initial number of KVs

### CODE REVIEW

File: lib/runtime/src/transports/etcd.rs
Comment (nnshah1) [inline lib/runtime/src/transports/etcd.rs:366]: would it also work to move this read / watch stream to before we get the start_revision?

Comment (nnshah1) [inline lib/runtime/src/transports/etcd.rs:359]: question: what happens if we don't include existing in the beginning - does that not get added later because of the start revision?

**Review by nnshah1 — APPROVED** [review]
Looks good - open question - can we alter the order so we start watching before we send the initial list of matches - instead of using unbounded
.

**Comment by rmccorm4** [comment]
Related: https://github.com/ai-dynamo/dynamo/pull/5128

File: lib/runtime/src/transports/etcd.rs [hunk 1]
```diff
@@ -348,20 +348,27 @@ impl Client {
         prefix: impl AsRef<str> + std::fmt::Display,
         include_existing: bool,
     ) -> Result<PrefixWatcher> {
-        let (tx, rx) = mpsc::channel(32);
+        let (tx, rx) = mpsc::channel(4096);
```
Comment (mohammedabdulwahhab) [inline lib/runtime/src/transports/etcd.rs]: Expanded channel bound. 32 is too small.

File: lib/runtime/src/transports/etcd.rs [hunk 2]
```diff
@@ -384,15 +391,16 @@ impl Client {
...
+    /// Returns the next revision to watch from and, if `include_existing` is true,
+    /// the existing keys with the prefix. Existing KVs should be sent to the consumer
+    /// before starting the watch to maintain ordering.
     async fn get_start_revision(
         &self,
         prefix: impl AsRef<str> + std::fmt::Display,
-        existing_kvs_tx: Option<&mpsc::Sender<WatchEvent>>,
-    ) -> Result<i64> {
+        include_existing: bool,
+    ) -> Result<(i64, Option<Vec<KeyValue>>)> {
```
Comment (mohammedabdulwahhab) [inline lib/runtime/src/transports/etcd.rs:398]: Modified this function to move the initial KVs back to the caller instead of writing them to tx

File: lib/runtime/src/transports/etcd.rs [hunk 3]
```diff
@@ -348,20 +348,27 @@ impl Client {
...
+        let (mut start_revision, existing_kvs) = self
+            .get_start_revision(prefix.as_ref(), include_existing)
             .await?;
 
         // Resilience watch stream in background
         let connector = self.connector.clone();
         let prefix_str = prefix.as_ref().to_string();
         self.rt.spawn(async move {
+            // Flush existing KVs first (before starting watch)
+            if let Some(kvs) = existing_kvs {
```
Comment (mohammedabdulwahhab) [inline lib/runtime/src/transports/etcd.rs]: Let's flush the keys in the background.

Comment (kthui) [reply lib/runtime/src/transports/etcd.rs]: This will shift the timing, but if the background task is performed before the `rx` is read, the deadlock can still happen?

Comment (mohammedabdulwahhab) [reply lib/runtime/src/transports/etcd.rs]: I'm not convinced that is the case.

Sure, the bg task can send first. If it sends less than 4096 entries, we're good.

If it tries to send more, it will wait until the channel is read from. This can now happen because the function is no longer blocked from returning `rx`.

Comment (kthui) [reply lib/runtime/src/transports/etcd.rs]: https://github.com/ai-dynamo/dynamo/pull/5091#discussion_r2663124112

File: lib/runtime/src/transports/etcd.rs (hunk 1 above)
Comment (kthui) [reply lib/runtime/src/transports/etcd.rs]: Maybe we don't need to increase the channel size, because the background sender will simply wait until the `rx` is read?

**Review by kthui — APPROVED** [review]

File: lib/runtime/src/transports/etcd.rs (hunk 3 above)
Comment (mohammedabdulwahhab) [reply lib/runtime/src/transports/etcd.rs]: Agreed that we can keep it the same. I imagine 4096 helps absorb backpressure in case of bursts better.

File: lib/runtime/src/transports/etcd.rs [hunk 4]
```diff
@@ -348,17 +348,28 @@ impl Client {
...
-                if include_existing { Some(&tx) } else { None },
-            )
+        let (mut start_revision, existing_kvs) = self
+            .get_start_revision(prefix.as_ref(), include_existing)
             .await?;
 
-        // Resilience watch stream in background
+        // Size channel to fit all existing KVs (avoids deadlock when sending before return)
+        let existing_count = existing_kvs.as_ref().map_or(0, |kvs| kvs.len());
+        let channel_size = std::cmp::max(32, existing_count + 32);
```
Comment (nnshah1) [inline lib/runtime/src/transports/etcd.rs]: question: won't this always be existing_count + 32 (assuming existin_count >=0)

**Review by nnshah1 — APPROVED** [review]

File: lib/runtime/src/transports/etcd.rs (hunk 4 above)
Comment (mohammedabdulwahhab) [reply lib/runtime/src/transports/etcd.rs]: Yes, fixed.

**Review by kthui — APPROVED** [review]

**Comment by dagil-nvidia** [comment]
Auto-linked to [DGH-479](https://linear.app/nvidia/issue/DGH-479)
