### PR TITLE
fix(kv-router): correct decode-worker scoring for unregistered workers in selector

### LINKED ISSUE #7836: [BUG]: KV router starves decode workers under single-turn inference workloads
### Describe the Bug

**Issue**: KV router starves decode workers under single-turn workloads                                                                                                                                                         
                                                                                                                                                                                                                              
  With `DYN_ROUTER_MODE: kv`, 1P/5D disaggregated setup `(Qwen3-32B-FP8 on H100)`, and `256-512` concurrent single-turn requests:                                                                                          
                                                                                                                                                                                                                              
  - 3 of 5 decode workers receive 100% of traffic (100% GPU util, 691-694W at TDP)                                                                                                                                            
  - 2 decode workers receive 0 requests (0% GPU util, 115-120W idle)
  - KV locality affinity has no benefit since requests are independent (no multi-turn cache reuse)                                                                                                                            
  - Router never bootstraps idle workers because they have no KV cache to attract traffic                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                               
  Env: Dynamo 0.9.1, vLLM runtime, NIXL connector, GKE H100 cluster. 

### Steps to Reproduce

1. Deploy DynamoGraphDeployment with DYN_ROUTER_MODE: kv, 1 prefill, 5 decode workers (1 GPU each), Qwen3-32B-FP8, NIXL connector                                                                                           
  2. Send single-turn (stateless) concurrent load:                                                                                                                                                                            
  locust -f locust_inferencex.py --host http://localhost:8000 \                                                                                                                                                               
      --headless -u 256 -r 256 -t 10m                                                                                                                                                                                         
  3. Observe per-worker GPU utilization:                                                                                                                                                                                      
  curl --data-urlencode \                                                                                                                                                                                                     
      'query=DCGM_FI_DEV_GPU_UTIL{namespace="vllm-disaggregated"}' \                                                                                                                                                          
      "http://<vm-url>:8428/api/v1/query"                                                                                                                                                                                     
  4. Result: 3 workers at 100% util / ~694W, 2 workers at 0% util / ~115W                                                                                                                                                     

### Expected Behavior

Expected: Even distribution across all decode workers for single-turn/stateless workloads.  

### Actual Behavior

- 3 of 5 decode workers receive 100% of traffic (100% GPU util, 691-694W at TDP)                                                                                                                                            
- 2 decode workers receive 0 requests (0% GPU util, 115-120W idle)

### Environment

 Env: Dynamo 0.9.1, vLLM runtime, NIXL connector, GKE H100 cluster. 

### Additional Context

_No response_

### Screenshots

<img width="1437" height="530" alt="Image" src="https://github.com/user-attachments/assets/aca1bd3c-1360-4edd-8dd0-5a1e8cc2a160" />

### PR DESCRIPTION
**Pull request by MatejKosec**
Fixes #7836

## Problem

Under single-turn workloads, `DefaultWorkerSelector` penalizes decode workers relative to unregistered peers. When `track_prefill_tokens=false`, unregistered workers get `isl` (input sequence length) as their default prefill_token fallback — making them appear 32x busier than registered idle workers. This steers requests away from decode workers even when they have capacity.

## Fix

1. `selector.rs`: Use 0 (not `isl`) as the default prefill_token for unregistered decode workers when `track_prefill_tokens=false`
2. `config.rs`: Fix stale doc comment (actual default is 4.0, not 2.0; min is >= 0.0)
3. `kv_router_args.py`: Fix help text (0.0 is a valid threshold)

Complements #7912 (latch busy detection) — that PR fixes when workers appear busy, this PR fixes how workers are scored for request routing.

## Tests

1 regression test: `test_help_text_allows_zero_threshold` — verifies the help text no longer misleadingly says "Must be > 0" (fails on pre-fix code, passes after).

Fixes #7836

### CODE REVIEW

**Comment by PeaBrane** [comment]
@MatejKosec I think the changes make sense. The new arg tests are a bit tautological and may be prone to breaking if we change internal impls. I'd omit them for now.

Will review the rest in a bit

File: lib/kv-router/src/scheduling/selector.rs [hunk 1]
```diff
@@ -145,7 +145,16 @@ impl<C: WorkerConfigLike> WorkerSelector<C> for DefaultWorkerSelector {
 
         let get_score = |worker: WorkerWithDpRank| -> f64 {
             let overlap = *overlaps.get(&worker).unwrap_or(&0);
-            let prefill_token = *prefill_tokens.get(&worker).unwrap_or(&isl);
+            // When track_prefill_tokens is false (e.g. decode workers in disaggregated mode),
```
Comment (PeaBrane) [inline lib/kv-router/src/scheduling/selector.rs]: this comment is a bit too bulky and too bug-specific, can be condensed

**Review by PeaBrane — APPROVED** [review]

**Comment by PeaBrane** [comment]
I buy the specific selector fix here, but I’m not sure we can conclusively say it fully fixes #7836 yet. As I understand the change, it addresses a startup / registration skew path where a worker is visible to selection before it has corresponding slot-tracker state, which can clearly bias routing against cold decode workers. That seems like a plausible contributor to the reported starvation pattern, but unless we have validation showing this was the dominant steady-state cause in the reported workload, I’d frame this as addressing one concrete bootstrap path behind #7836 rather than definitively closing the broader issue.

**Comment by PeaBrane** [comment]
/ok to test [6a65b7c](https://github.com/ai-dynamo/dynamo/pull/7919/commits/6a65b7cab341960fb7464b0c31a578699b7dcce1)
