### PR TITLE
fix(operator): vLLM multi-node support for TP and DP 

### LINKED ISSUE #4934: [BUG]: vllm multi-node tp/pp not working with vllm v0.12.0
### Describe the Bug

When running with a dynamo vllm runtime running v0.12.0 and the advertised vllm [dissagg_multinode.yaml](https://github.com/ai-dynamo/dynamo/blob/0de75a872338131510f2f400bd5ec5f7797d3394/examples/backends/vllm/deploy/disagg-multinode.yaml), the Leader logs show it hitting the following error:

```
 File "/opt/dynamo/venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 123, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ParallelConfig
  Value error, Tensor parallel size (2) cannot be larger than the number of available GPUs (1). [type=value_error, input_value=ArgsKwargs((), {'pipeline...'_api_process_rank': 0}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.11/v/value_error
stream closed: EOF for tm/vllm-agg-0-vllmdecodeworker-0-vllmdecodeworker-ldr-chfdw (main)
```

### Steps to Reproduce

For the issue with vllm v0.12.0 I have the following DynamoGraphDeployment:

```yaml
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-agg
spec:
  pvcs:
    - name: model-cache
      create: false
  services:
    Frontend:
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidian/dynamo-dev/vllm-runtime:tm-69817c2d9
    decode:
      componentType: worker
      volumeMounts:
        - name: model-cache
          mountPoint: /opt/models
      replicas: 1
      multinode:
        nodeCount: 2
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidian/dynamo-dev/vllm-runtime:tm-69817c2d9
          workingDir: /workspace/examples/backends/vllm
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model 
            - "${MODEL_PATH}"
            - --served-model-name
            - Qwen/Qwen3-0.6B
            - --tensor-parallel-size 
            - "2" 
          env:
          - name: MODEL_PATH
            value: "/opt/models/hub/models--Qwen--Qwen3-0.6B/snapshots/c1899de289a04d12100db370d81485cdf75e47ca"
          - name: HF_HOME
            value: /opt/models
    prefill:
      componentType: worker
      volumeMounts:
        - name: model-cache
          mountPoint: /opt/models
      replicas: 1
      multinode:
        nodeCount: 2
      resources:
        limits:
          gpu: "1"
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidian/dynamo-dev/vllm-runtime:tm-69817c2d9
          workingDir: /workspace/examples/backends/vllm
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model 
            - "${MODEL_PATH}"
            - --served-model-name
            - Qwen/Qwen3-0.6B
            - --is-prefill-worker
            - --tensor-parallel-size 
            - "2" 
          env:
          - name: MODEL_PATH
            value: "/opt/models/hub/models--Qwen--Qwen3-0.6B/snapshots/c1899de289a04d12100db370d81485cdf75e47ca"
          - name: HF_HOME
            value: /opt/models
```

You will need to build a vllm runtime image from commit [69817c2d9cb4e10262c4f6924e73cc9ad68e52cb](https://github.com/ai-dynamo/dynamo/tree/69817c2d9cb4e10262c4f6924e73cc9ad68e52cb) since this is post 0.7.0 release. You can do this downloading the repo, checking out the commit, and then running:

```
./container/build.sh --framework VLLM --tag `<your-image-tag>`
```

Then push to your registry. Substitute `nvcr.io/nvidian/dynamo-dev/vllm-runtime:tm-69817c2d9` with `<your-image-tag>` in the DGD.

Apply manifest and get the leader Pod logs for either the prefill or decode. Both hit the same error. 

```
kubectl logs vllm-agg-0-prefill-0-prefill-ldr-<hash> -n <k8s-ns>
```

You will see the following error:

```
2025-12-12 19:44:58,878	WARNING services.py:2137 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 8589934592 bytes available. This will harm performance! You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you can increase /dev/shm size by passing '--shm-size=10.24gb' to 'docker run' (or add it to the run_options list in a Ray cluster config). Make sure to set this to more than 30% of available RAM.
2025-12-12 19:44:56,905	INFO usage_lib.py:473 -- Usage stats collection is enabled by default without user confirmation because this terminal is detected to be non-interactive. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.
2025-12-12 19:44:56,905	INFO scripts.py:919 -- Local node IP: 10.2.30.146
2025-12-12 19:44:59,010	SUCC scripts.py:963 -- --------------------
2025-12-12 19:44:59,010	SUCC scripts.py:964 -- Ray runtime started.
2025-12-12 19:44:59,011	SUCC scripts.py:965 -- --------------------
2025-12-12 19:44:59,011	INFO scripts.py:967 -- Next steps
2025-12-12 19:44:59,011	INFO scripts.py:970 -- To add another node to this Ray cluster, run
2025-12-12 19:44:59,011	INFO scripts.py:973 --   ray start --address='10.2.30.146:6379'
2025-12-12 19:44:59,011	INFO scripts.py:982 -- To connect to this Ray cluster:
2025-12-12 19:44:59,011	INFO scripts.py:984 -- import ray
2025-12-12 19:44:59,011	INFO scripts.py:985 -- ray.init()
2025-12-12 19:44:59,011	INFO scripts.py:1016 -- To terminate the Ray runtime, run
2025-12-12 19:44:59,011	INFO scripts.py:1017 --   ray stop
2025-12-12 19:44:59,011	INFO scripts.py:1020 -- To view the status of the cluster, use
2025-12-12 19:44:59,011	INFO scripts.py:1021 --   ray status
[2025-12-12 19:45:12] INFO __init__.py:53: dynamo.nixl_connect: Utilizing CuPy to enable GPU acceleration.
[2025-12-12 19:45:12] INFO encode_worker_handler.py:30: Using cupy for array operations (GPU mode).
[2m2025-12-12T19:45:12.843242Z[0m [33m WARN[0m [2mdynamo_runtime::config[0m[2m:[0m DYN_SYSTEM_USE_ENDPOINT_HEALTH_STATUS is deprecated and no longer used. System health is now determined by endpoints that register with health check payloads. Please update your configuration to register health check payloads directly on endpoints.
[2m2025-12-12T19:45:12.843280Z[0m [33m WARN[0m [2mdynamo_runtime::config[0m[2m:[0m DYN_SYSTEM_ENABLED is deprecated. System metrics server is now controlled solely by DYN_SYSTEM_PORT. Set DYN_SYSTEM_PORT to a positive value to enable the server, or set to -1 to disable (default).
[2m2025-12-12T19:45:12.873269Z[0m [33m WARN[0m [2mdynamo_runtime::config[0m[2m:[0m DYN_SYSTEM_USE_ENDPOINT_HEALTH_STATUS is deprecated and no longer used. System health is now determined by endpoints that register with health check payloads. Please update your configuration to register health check payloads directly on endpoints.
[2m2025-12-12T19:45:12.873285Z[0m [33m WARN[0m [2mdynamo_runtime::config[0m[2m:[0m DYN_SYSTEM_ENABLED is deprecated. System metrics server is now controlled solely by DYN_SYSTEM_PORT. Set DYN_SYSTEM_PORT to a positive value to enable the server, or set to -1 to disable (default).
[2m2025-12-12T19:45:12.873533Z[0m [32m INFO[0m [2mdynamo_runtime::distributed[0m[2m:[0m Initializing KV store discovery backend
[2m2025-12-12T19:45:12.873631Z[0m [32m INFO[0m [2mdynamo_runtime::pipeline::network::manager[0m[2m:[0m Initializing NetworkManager [3mmode[0m[2m=[0mnats [3mhttp_port[0m[2m=[0m8888 [3mtcp_port[0m[2m=[0m9999
[2m2025-12-12T19:45:12.874058Z[0m [32m INFO[0m [2mdynamo_runtime::system_status_server[0m[2m:[0m [spawn_system_status_server] binding to: 0.0.0.0:9090
[2m2025-12-12T19:45:12.874090Z[0m [32m INFO[0m [2mdynamo_runtime::system_status_server[0m[2m:[0m [spawn_system_status_server] system status server bound to: 0.0.0.0:9090
[2m2025-12-12T19:45:12.874106Z[0m [32m INFO[0m [2mdynamo_runtime::distributed[0m[2m:[0m System status server started successfully on 0.0.0.0:9090
[2m2025-12-12T19:45:12.874804Z[0m [32m INFO[0m [2margs.create_kv_transfer_config[0m[2m:[0m Creating kv_transfer_config from --connector ['nixl']
[2m2025-12-12T19:45:12.874920Z[0m [32m INFO[0m [2margs.create_kv_events_config[0m[2m:[0m Using env-var DYN_VLLM_KV_EVENT_PORT=20080 to create kv_events_config
[2m2025-12-12T19:45:12.874980Z[0m [32m INFO[0m [2margs.overwrite_args[0m[2m:[0m Using kv_events_config for publishing vLLM kv events over zmq: KVEventsConfig(enable_kv_cache_events=True, publisher='zmq', endpoint='tcp://*:20080', replay_endpoint=None, buffer_steps=10000, hwm=100000, max_queue_size=100000, topic='')
[2m2025-12-12T19:45:13.132087Z[0m [32m INFO[0m [2mdynamo_runtime::distributed[0m[2m:[0m Added NATS service tm-vllm-agg_prefill
WARNING 12-12 19:45:13 [prometheus.py:31] Found PROMETHEUS_MULTIPROC_DIR was set by user. This directory must be wiped between vLLM runs or you will find inaccurate metrics. Unset the variable and vLLM will properly handle cleanup.
INFO 12-12 19:45:19 [model.py:637] Resolved architecture: Qwen3ForCausalLM
INFO 12-12 19:45:19 [model.py:1750] Using max model len 40960
WARNING 12-12 19:45:19 [model.py:1576] Default sampling parameters have been overridden by the model's Hugging Face generation config recommended from the model creator. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
INFO 12-12 19:45:19 [model.py:637] Resolved architecture: Qwen3ForCausalLM
INFO 12-12 19:45:19 [model.py:1750] Using max model len 40960
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/components/src/dynamo/vllm/__main__.py", line 7, in <module>
    main()
  File "/workspace/components/src/dynamo/vllm/main.py", line 799, in main
    uvloop.run(worker())
  File "/opt/dynamo/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/dynamo/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/workspace/components/src/dynamo/vllm/main.py", line 102, in worker
    await init_prefill(runtime, config)
  File "/workspace/components/src/dynamo/vllm/main.py", line 376, in init_prefill
    ) = setup_vllm_engine(config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/components/src/dynamo/vllm/main.py", line 272, in setup_vllm_engine
    vllm_config = engine_args.create_engine_config(usage_context=usage_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/dynamo/venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 1580, in create_engine_config
    parallel_config = ParallelConfig(
                      ^^^^^^^^^^^^^^^
  File "/opt/dynamo/venv/lib/python3.12/site-packages/pydantic/_internal/_dataclasses.py", line 123, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ParallelConfig
  Value error, Tensor parallel size (2) cannot be larger than the number of available GPUs (1). [type=value_error, input_value=ArgsKwargs((), {'pipeline...'_api_process_rank': 0}), input_type=ArgsKwargs]
    For further information visit https://errors.pydantic.dev/2.11/v/value_error
[2m2025-12-12T19:45:20.469133Z[0m [31mERROR[0m [1mhttp-request[0m: [2mtower_http::trace::on_failure[0m[2m:[0m response failed [3mclassification[0m[2m=[0mStatus code: 503 Service Unavailable [3mlatency[0m[2m=[0m0 ms [2m[3mmethod[0m[2m=[0mGET [3muri[0m[2m=[0m/live [3mversion[0m[2m=[0mHTTP/1.1[0m

```

The Leader Pod then hits `CrashLoopBackoff`.

### Expected Behavior

All of the worker Pods should hit Ready state, the model is registered with the Frontend and that inference on the model works successfully. (Can successfully complete an OAI chat completion request)

### Actual Behavior

Included in Steps to Reproduce

### Environment

CRD/Platform/Operator version:  `0.7.0`
vllm runtime image built from commit [69817c2d9cb4e10262c4f6924e73cc9ad68e52cb](https://github.com/ai-dynamo/dynamo/tree/69817c2d9cb4e10262c4f6924e73cc9ad68e52cb)

### Additional Context

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by MatejKosec**
## Summary

Fixes vLLM multi-node deployments in the operator for both tensor/pipeline parallel (TEP) and data parallel (DEP) modes:

- **TEP**: Use Ray distributed executor backend so vLLM can spawn workers across nodes
- **DEP**: Use hybrid load balancing mode where each node runs its own DP coordinator

Also fixes K8s DNS compatibility by lowercasing service names in Grove hostnames.

Fixes #4934, DYN-1620

### CODE REVIEW

**Comment by MatejKosec** [comment]
## Tested DEP 16 Disaggregated Deployment

Here is the DGD for reproducibility

### Configuration Used

```yaml
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: dep16d
  namespace: mkosec-dynamo
spec:
  backendFramework: vllm
  envs:
    - name: HF_HOME
      value: /model-cache
    - name: VLLM_CACHE_ROOT
      value: /model-cache/.vllm-cache
  pvcs:
    - name: model-cache
      create: false
  services:
    Frontend:
      dynamoNamespace: dep16d
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidian/dynamo-dev/vllm-runtime:mkosec-fix-4934
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 1800
            failureThreshold: 60

    # Prefill workers - DEP 16 with DeepEP
    Prefill:
      dynamoNamespace: dep16d
      componentType: worker
      subComponentType: prefill
      replicas: 1
      multinode:
        nodeCount: 2
      resources:
        limits:
          gpu: "8"
      volumeMounts:
        - name: model-cache
          mountPoint: /model-cache
      sharedMemory:
        size: 80Gi
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidian/dynamo-dev/vllm-runtime:mkosec-fix-4934
          resources:
            limits:
              rdma/shared_ib: "1"
            requests:
              rdma/shared_ib: "1"
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 600
          workingDir: /workspace/dynamo
          env:
            - name: VLLM_USE_DEEP_GEMM
              value: "0"
            - name: VLLM_MOE_USE_DEEP_GEMM
              value: "0"
            - name: VLLM_MOE_DP_CHUNK_SIZE
              value: "256"
            - name: VLLM_SKIP_P2P_CHECK
              value: "1"
            - name: GLOO_SOCKET_IFNAME
              value: eth0
            - name: VLLM_DEEPEP_BUFFER_SIZE_MB
              value: "1024"
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model
            - deepseek-ai/DeepSeek-R1
            - --served-model-name
            - deepseek-ai/DeepSeek-R1
            - --tensor-parallel-size
            - "1"
            - --data-parallel-size
            - "16"
            - --enable-expert-parallel
            - --all2all-backend
            - deepep_low_latency
            - --is-prefill-worker
            - --no-enable-prefix-caching
            - --max-model-len
            - "8192"
            - --max-num-seqs
            - "128"
            - --gpu-memory-utilization
            - "0.85"

    # Decode workers - DEP 16 with DeepEP
    Decode:
      dynamoNamespace: dep16d
      componentType: worker
      subComponentType: decode
      replicas: 1
      multinode:
        nodeCount: 2
      resources:
        limits:
          gpu: "8"
      volumeMounts:
        - name: model-cache
          mountPoint: /model-cache
      sharedMemory:
        size: 80Gi
      extraPodSpec:
        mainContainer:
          image: nvcr.io/nvidian/dynamo-dev/vllm-runtime:mkosec-fix-4934
          resources:
            limits:
              rdma/shared_ib: "1"
            requests:
              rdma/shared_ib: "1"
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 600
          workingDir: /workspace/dynamo
          env:
            - name: VLLM_USE_DEEP_GEMM
              value: "0"
            - name: VLLM_MOE_USE_DEEP_GEMM
              value: "0"
            - name: VLLM_MOE_DP_CHUNK_SIZE
              value: "256"
            - name: VLLM_SKIP_P2P_CHECK
              value: "1"
            - name: GLOO_SOCKET_IFNAME
              value: eth0
            - name: VLLM_DEEPEP_BUFFER_SIZE_MB
              value: "1024"
          command:
            - python3
            - -m
            - dynamo.vllm
          args:
            - --model
            - deepseek-ai/DeepSeek-R1
            - --served-model-name
            - deepseek-ai/DeepSeek-R1
            - --tensor-parallel-size
            - "1"
            - --data-parallel-size
            - "16"
            - --enable-expert-parallel
            - --all2all-backend
            - deepep_low_latency
            - --enable-prefix-caching
            - --max-model-len
            - "8192"
            - --max-num-seqs
            - "128"
            - --gpu-memory-utilization
            - "0.85"
```

File: deploy/cloud/operator/internal/dynamo/backend_vllm.go [hunk 1]
```diff
@@ -98,37 +98,85 @@ func injectRayDistributedLaunchFlags(container *corev1.Container, role Role, ser
...
+			}
+		}
+		return false
+	}
+
 	switch role {
+	case RoleLeader:
+		// Leader runs API server + coordinator + local engines
+		// Hybrid LB mode: local DP coordination within node, Dynamo routes between nodes
+		flags = []string{"--data-parallel-hybrid-lb"}
```
Comment (alec-flowers) [inline deploy/cloud/operator/internal/dynamo/backend_vllm.go:147]: Dynamo router will also select the DP worker and pass it in to the generate() function. Is that still respected in this mode?
https://github.com/ai-dynamo/dynamo/blob/main/components/src/dynamo/vllm/handlers.py#L782

I am assuming so just wanted to check.

Comment (alec-flowers) [reply deploy/cloud/operator/internal/dynamo/backend_vllm.go:147]: I just checked and it should be fine.

File: docs/kubernetes/api_reference.md [hunk 2]
```diff
@@ -1068,7 +1069,7 @@ Default container ports are configured based on component type:
 ## Backend-Specific Configurations
 
 ### VLLM
-- **Ray Head Port**: 6379 (for Ray-based multinode deployments)
+- **Ray Head Port**: 6379 (for Ray cluster coordination in multinode TP/PP deployments)
```
Comment (alec-flowers) [inline docs/kubernetes/api_reference.md:1072]: Can this be changed by an env var or an argument?

**Review by alec-flowers — APPROVED** [review]
lgtm! Thanks for getting this working again. Super important for our large scale deployments.

**Review by biswapanda — APPROVED** [review]
