### PR TITLE
fix(frontend): reconstruct tool-call arguments split across streaming deltas

### LINKED ISSUE #8640: Non-stream chat completions return tool_calls with empty arguments
## Summary

Non-stream chat completions return tool calls with `arguments: ""` instead of the model-produced JSON. The aggregator drops every argument-fragment delta.

## Details

OpenAI-streaming producers (vLLM hermes, SGLang, etc.) split a single tool call across multiple deltas — the first carries `id` + `type` + `function.name`, and follow-ups carry `function.arguments` fragments with no `id` / `name`. Example stream for one `get_weather({"city":"Tokyo"})` call:

```jsonc
// delta 1 — opens the call
{"index": 0, "id": "tc1", "type": "function", "function": {"name": "get_weather"}}
// delta 2 — argument fragment
{"index": 0, "function": {"arguments": "{\"city\":"}}
// delta 3 — argument fragment
{"index": 0, "function": {"arguments": "\"Tokyo\"}"}}
```

The old `convert_tool_chunk_to_message_tool_call` required `id`, `name`, **and** `arguments` all on the same chunk. Its `filter_map` discarded every chunk above: delta 1 had no `arguments`; deltas 2 and 3 had no `id` or `name`. Clients see:

```json
{"id": "tc1", "type": "function", "function": {"name": "get_weather", "arguments": ""}}
```

Streaming path is unaffected (doesn't go through the non-stream aggregator).

## Repro

100% repro on every tool prompt when running with `--dyn-chat-processor vllm`.

## Expected

Aggregator should merge chunks by `index` — `id`/`type`/`function.name` first-wins, `function.arguments` concatenated across fragments — and emit the final `ChatCompletionMessageToolCall` with the full JSON payload.

### PR DESCRIPTION
**Pull request by keivenchang**
#### Overview:

Non-stream chat completions return tool calls with `arguments: ""` instead of the real JSON, because the aggregator drops every argument-fragment delta. This PR aggregates them correctly.

#### What's broken:

OpenAI-streaming producers (vLLM hermes, SGLang, etc.) split a single tool call across multiple deltas — the first carries `id` + `type` + `function.name`, and follow-ups carry `function.arguments` **fragments** with no `id` / `name`. Example stream for one `get_weather({"city":"Tokyo"})` call:

```jsonc
// delta 1 — opens the call
{"index": 0, "id": "tc1", "type": "function", "function": {"name": "get_weather"}}
// delta 2 — argument fragment
{"index": 0, "function": {"arguments": "{\"city\":"}}
// delta 3 — argument fragment
{"index": 0, "function": {"arguments": "\"Tokyo\"}"}}
```

The old `convert_tool_chunk_to_message_tool_call` required `id`, `name`, **and** `arguments` all on the *same* chunk. Its `filter_map` discarded every chunk above: delta 1 had no `arguments`; deltas 2 and 3 had no `id` or `name`. Result seen by clients:

```json
{"id": "tc1", "type": "function", "function": {"name": "get_weather", "arguments": ""}}
```

`arguments: ""` — model's JSON payload silently dropped. 100% repro on every tool prompt under Scenario 3 (`--dyn-chat-processor vllm`). Streaming path works fine because it doesn't go through the non-stream aggregator.

#### What this PR does:

Aggregate the deltas by `index` before converting to the final schema:

- Replace `convert_tool_chunk_to_message_tool_call` with a per-index `BTreeMap` accumulator on `DeltaChoice`.
- During fold: merge chunks sharing the same `index` — `id` / `type` / `function.name` first-wins, `function.arguments` **concatenated** across fragments.
- After fold: `finalize_merged_tool_chunk` emits the aggregated `ChatCompletionMessageToolCall`. Missing `arguments` defaults to `""` (legal empty-args case); missing `id` or `name` drops the call with a `tracing::warn!` instead of silently.

For the example above, delta 1 opens the accumulator entry, deltas 2 and 3 append their fragments, and the final response carries `arguments: "{\"city\":\"Tokyo\"}"`.

#### Where should the reviewer start?

`lib/llm/src/protocols/openai/chat_completions/aggregator.rs`

#### Related Issues:

Closes #8640

Internal tracking: DIS-1809

/coderabbit profile chill

### CODE REVIEW

**Comment by keivenchang** [comment]
@coderabbitai all three addressed in 6215206:

- **346-360 unreachable extend branch** — simplified to unconditional assign, added a comment explaining why the Some branch cant happen here (tool_calls is None on entry, try_tool_call_parse_aggregate writes strictly after this loop).
- **824-854 assertion** — tightened to strict is_none(). Ya youre right, finalization never assigns Some(vec![]), so the disjunction was papering over a regression we'd want to catch.
- **108-112 r#type** — threaded through finalize_merged_tool_chunk as chunk.r#type.unwrap_or(FunctionType::Function). Picked forward-compat over 'drop the merge' since Function is currently the only variant but that could change upstream.

18/18 aggregator tests still green.

**Review by richardhuo-nv — APPROVED** [review]

File: lib/llm/src/protocols/openai/chat_completions/aggregator.rs [hunk 1]
```diff
@@ -56,7 +56,18 @@ struct DeltaChoice {
...
     logprobs: Option<dynamo_protocols::types::ChatChoiceLogprobs>,
-    // Optional tool calls for the chat choice.
+    // Tool-call chunks accumulated in the order they arrived from the stream,
+    // keyed by `index` so chunks that carry only argument fragments can be
+    // merged into the entry created by the initial (id + name) chunk.
+    // BTreeMap preserves deterministic iteration order on the index dimension.
+    // See [`merge_tool_call_chunk`] for per-field merge semantics.
+    // DIS-1809: replaces the old `Option<Vec<ChatCompletionMessageToolCall>>`
+    // which required id/name/arguments to all be set on the same chunk.
+    tool_call_chunks: BTreeMap<u32, dynamo_protocols::types::ChatCompletionMessageToolCallChunk>,
```
Comment (KrishnanPrash) [inline lib/llm/src/protocols/openai/chat_completions/aggregator.rs]: Should we remove references to the ticket in the PR or are these left intentionally?

File: lib/llm/src/protocols/openai/chat_completions/aggregator.rs [hunk 2]
```diff
@@ -169,6 +256,7 @@ impl DeltaAggregator {
                                     finish_reason: None,
                                     stop_reason: None,
                                     logprobs: None,
+                                    tool_call_chunks: BTreeMap::new(),
```
Comment (KrishnanPrash) [inline lib/llm/src/protocols/openai/chat_completions/aggregator.rs:259]: Cool to see a `BTreeMap` here! IIUC we're using it because it naturally maintains order with `O(log n)` inserts.

A question that crossed my mind: is maintaining ordering of `tool_calls` actually necessary? Clients would need to identify tool calls by id anyway? how does standalone vLLM/SGLang handle this?

If we don't need ordering, we could just use a HashMap instead of a BTreeMap here.

**Review by KrishnanPrash — APPROVED** [review]
Overall LGTM 🚀 , just a question about data structure choice for my own understanding

File: lib/llm/src/protocols/openai/chat_completions/aggregator.rs (hunk 2 above)
Comment (keivenchang) [reply lib/llm/src/protocols/openai/chat_completions/aggregator.rs:259]: yeah ordering matters here. OpenAI streaming spec gives each tool-call chunk an explicit `index: u32` and clients reconstructing the final `tool_calls` array expect it ordered by that index — vLLM/SGLang both emit in index order and downstream consumers rely on it (first tool-call in array matches first prompted tool, etc.). clients do key by id too but that's the addressing path, not the array-shape expectation.

could use HashMap + sort-at-finalize, but BTreeMap's O(log n) insert is basically free at our N (typically 1-8 tool calls per response) and keeps the invariant local to the data structure rather than relying on every future edit to remember to sort. picked BTreeMap for that reason.

File: lib/llm/src/protocols/openai/chat_completions/aggregator.rs (hunk 1 above)
Comment (keivenchang) [reply lib/llm/src/protocols/openai/chat_completions/aggregator.rs]: good catch — you're right, Linear refs shouldn't be in public code. filed [#8640](https://github.com/ai-dynamo/dynamo/issues/8640) and [#8636](https://github.com/ai-dynamo/dynamo/issues/8636) as the public-facing issues, and swapped every DIS-1809 / DIS-1810 in the file over to those (comments, test name, doc link). also renamed the repro test to `test_issue_8640_...`. pushed in 5258955d865.
