### PR TITLE
fix: use channel to avoid race condition from async nats registration task

### LINKED ISSUE #4753: [BUG]: NATS request-plane race condition on registration maybe
### Describe the Bug

There seems to be an error on worker startup with the NATS service, on latest main.

I have seen it work occasionally, so likely a race condition.

### Steps to Reproduce

Clear etcd. Restart nats. Run this:

`python -m dynamo.sglang --model-path Qwen/Qwen3-0.6B` 

Gives this output.

```
2025-12-04T14:55:38.090064Z  INFO main.init: Registering model with endpoint types: chat,completions
2025-12-04T14:55:38.090222Z DEBUG dynamo_runtime::local_endpoint_registry: Registering local endpoint: generate
2025-12-04T14:55:38.090253Z DEBUG dynamo_runtime::component::endpoint: Registered engine for endpoint 'generate' in local registry
2025-12-04T14:55:38.090457Z  INFO register._get_runtime_config: Got total KV blocks from scheduler: 750229 (max_total_tokens=750229, page_size=1)
2025-12-04T14:55:38.090712Z DEBUG dynamo_runtime::component::endpoint: Starting endpoint: dynamo/backend/generate
2025-12-04T14:55:38.098016Z DEBUG dynamo_llm::local_model: Registering MDC at path: dynamo/backend/generate/694d9adb9d05322d
2025-12-04T14:55:38.098130Z DEBUG dynamo_runtime::discovery::kv_store: KVStoreDiscovery::register: Registering base model instance_id=7587891215212032557, namespace=dynamo, component=backend, endpoint=generate, key=dynamo/backend/generate/694d9adb9d05322d
2025-12-04T14:55:38.098188Z DEBUG dynamo_runtime::discovery::kv_store: KVStoreDiscovery::register: Serialized instance to 1584 bytes for key=dynamo/backend/generate/694d9adb9d05322d
2025-12-04T14:55:38.098196Z DEBUG dynamo_runtime::discovery::kv_store: KVStoreDiscovery::register: Getting/creating bucket=v1/mdc for key=dynamo/backend/generate/694d9adb9d05322d
2025-12-04T14:55:38.098212Z DEBUG dynamo_runtime::discovery::kv_store: KVStoreDiscovery::register: Inserting into bucket=v1/mdc, key=dynamo/backend/generate/694d9adb9d05322d
2025-12-04T14:55:38.098543Z  INFO dynamo_llm::kv_router::publisher: Registered KvStats Prometheus metrics
2025-12-04T14:55:38.098540Z  INFO dynamo_runtime::component::endpoint: Endpoint starting with request plane mode: nats
2025-12-04T14:55:38.098661Z DEBUG dynamo_runtime::component::endpoint: Registering endpoint health check target endpoint_name=generate
2025-12-04T14:55:38.098802Z DEBUG dynamo_runtime::component::endpoint: Registering endpoint 'generate' with graceful shutdown tracker
2025-12-04T14:55:38.098846Z DEBUG dynamo_runtime::utils::graceful_shutdown: Endpoint registered, total active: 0 -> 1
2025-12-04T14:55:38.098897Z  INFO dynamo_runtime::pipeline::network::manager: Creating NATS request plane server
2025-12-04T14:55:38.098991Z  INFO dynamo_runtime::component::endpoint: Registering endpoint with request plane server endpoint=generate transport="nats"
2025-12-04T14:55:38.099046Z  INFO dynamo_runtime::pipeline::network::ingress::nats_server: NatsMultiplexedServer::register_endpoint called endpoint_name=generate namespace=dynamo component=backend instance_id=7587891215212032557
2025-12-04T14:55:38.099106Z DEBUG dynamo_runtime::pipeline::network::ingress::nats_server: Looking up service group in registry service_name_raw=dynamo_backend service_name=dynamo_backend
2025-12-04T14:55:38.099543Z ERROR main.init: Failed to serve endpoints: Service 'dynamo_backend' not found in registry
2025-12-04T14:55:38.099592Z  INFO main.init: Metrics task succesfully cancelled
2025-12-04T14:55:38.100186Z  INFO dynamo_runtime::distributed: Added NATS service dynamo_backend
2025-12-04T14:55:38.107282Z  INFO decode_handler.cleanup: Engine shutdown
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/grahamk/src/dynamo/main/components/src/dynamo/sglang/__main__.py", line 7, in <module>
    main()
  File "/home/grahamk/src/dynamo/main/components/src/dynamo/sglang/main.py", line 530, in main
    uvloop.run(worker())
  File "/home/grahamk/venv/sglang-0.5.4/lib/python3.12/site-packages/uvloop/__init__.py", line 96, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/grahamk/venv/sglang-0.5.4/lib/python3.12/site-packages/uvloop/__init__.py", line 48, in wrapper
    return await main
           ^^^^^^^^^^
  File "/home/grahamk/src/dynamo/main/components/src/dynamo/sglang/main.py", line 97, in worker
    await init(runtime, config)
  File "/home/grahamk/src/dynamo/main/components/src/dynamo/sglang/main.py", line 175, in init
    await asyncio.gather(
Exception: Service 'dynamo_backend' not found in registry
```
 
It's definitely NATS:
- `--store-kv etcd --request-plane tcp` works
- `--store-kv file --request-plane nats` fails

### PR DESCRIPTION
**Pull request by biswapanda**
#### Overview:

This PR fixes race condition with nats stats service initializations

fixes: https://github.com/ai-dynamo/dynamo/issues/4753
closes: DYN-1541

#### Details 

* Root cause : `Write path` happens in a background job in asynchronously (fire & fortget task) and `Read path` during endpoint registration may/may-not find the service entry due to async / non-blocking nature of write/read path.

in PR ( https://github.com/ai-dynamo/dynamo/pull/4513)  write path for  add_stats_service  was moved from

- from [synchronous](https://github.com/ai-dynamo/dynamo/commit/f05f7629f#diff-f211ff34656da2ac111a1b346b1402d3221c1013b4255ee07316a5a6a42c0947L91-L95) awaits

```
component.add_stats_service().await?
```

- to async secondary runtime as a [background task](https://github.com/ai-dynamo/dynamo/commit/f05f7629f#diff-6802c89f8e7a78c1dfa7f7ab1806dcc1f0e2e18a5c261442264600497f8d8839R437)
```
component.drt().runtime().secondary().spawn(async move {
                if let Err(err) = c.add_stats_service().await {
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved NATS service registration handling to ensure proper initialization before services are accessed, enhancing reliability in distributed deployments.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

## Summary by CodeRabbit

* **Bug Fixes**
  * Service registration now provides a completion signal and can be awaited, returning success or a clear error when registration fails.
  * Improves reliability during startup by ensuring services are registered before being used and surfaces registration errors for easier troubleshooting.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: lib/runtime/src/component.rs [hunk 1]
```diff
@@ -275,10 +275,36 @@ impl ComponentBuilder {
...
+                None => {
+                    return Err(anyhow::anyhow!(
+                        "NATS service registration channel closed unexpectedly for component '{}'",
+                        component.service_name()
+                    ));
+                }
+            }
         }
         Ok(component)
     }
```
[the remark this answers is not in the document]
Comment (biswapanda) [reply lib/runtime/src/component.rs:312]: fixed [67aa299](https://github.com/ai-dynamo/dynamo/pull/4758/commits/67aa2991c6f9186b6b9cb162195045975d1bb09b)

**Comment by biswapanda** [comment]
@coderabbit review

File: lib/runtime/src/component.rs [hunk 2]
```diff
@@ -275,10 +275,38 @@ impl ComponentBuilder {
...
+        // before it's registered in the component registry.
         let drt = component.drt();
         if drt.request_plane().is_nats() {
-            drt.register_nats_service(component.clone());
+            let mut rx = drt.register_nats_service(component.clone());
+            // Wait synchronously for the NATS service registration to complete.
+            // Uses block_in_place() to safely call blocking_recv() from async contexts.
+            // This temporarily moves the current task off the runtime thread to allow
+            // blocking without deadlocking the runtime.
+            let result = tokio::task::block_in_place(|| rx.blocking_recv());
```
Comment (keivenchang) [inline lib/runtime/src/component.rs:288]: I tried but getting stuck at:
```
2025-12-05T01:13:34.984909Z  INFO dynamo_runtime::distributed: Added NATS service dynamo_backend
2025-12-05T01:13:44.972849Z  INFO dynamo_runtime::health_check: Canary timer expired for generate, sending health check

thread 'tokio-runtime-worker' panicked at /workspace/lib/runtime/src/component.rs:287:22:
Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<stuck>
```

Comment (keivenchang) [reply lib/runtime/src/component.rs:288]: Ok nevermind, you just switched from 
```
            match rx.blocking_recv() {   // panic!
```
to the block_in_place so you don't panic with the "blocking current thread while thread is running" error. Ok thank you, I think this works.

**Review by keivenchang — APPROVED** [review]

File: lib/runtime/src/component.rs (hunk 2 above)
Comment (biswapanda) [reply lib/runtime/src/component.rs:288]: yes, switched to `tokio::task::block_in_place(|| rx.blocking_recv())`  to allow blocking from async contexts. 
I didn't want async/await to spread across the codebase.
