### PR TITLE
fix: LoRA unregister drops all the LoRA variants that share the same ID

### LINKED ISSUE #7758: runtime_config_watch: unregistering a single LoRA can remove runtime config for the entire worker
`runtime_config_watch()` watches `EndpointModels`, but it currently reduces model-card events using `watch_and_extract_field()`, which keys state only by raw `instance_id`.

That is incorrect for LoRA-enabled workers. Model-card identity is `(namespace, component, endpoint, instance_id, model_suffix)`, so these are distinct discovery objects:

- base model card: `(..., instance_id, None)`
- LoRA model card: `(..., instance_id, Some(suffix))`

Because the watch state is keyed only by `instance_id`, unregistering a single LoRA can remove the runtime config for the entire worker, even when:

- the base model card still exists
- other LoRA cards still exist
- the worker endpoint is still healthy

## Impact

- healthy workers can become unroutable
- base model and remaining adapters can return `500 no endpoints available to route work`
- ordinary LoRA unload/unregister activity can trigger it

## Minimal repro

1. Register base model card for worker `X`.
2. Register LoRA `A` and LoRA `B` on the same `instance_id`.
3. Unregister LoRA `A`.
4. Observe the runtime-config watch drop worker `X`.

## Expected behavior

Worker runtime config should follow base-worker lifecycle, not adapter churn. Removing a LoRA should not delete the worker runtime config; only removing the base model card should.

## Root cause

The watcher is collapsing distinct model-card identities into `HashMap<instance_id, runtime_config>` and removing entries on `id.instance_id()`.

### PR DESCRIPTION
**Pull request by keivenchang**
#### Overview:

Fix `watch_and_extract_field()` so unregistering a LoRA adapter no longer wipes the runtime config for the entire worker.

#### Details:

- Change internal state from `HashMap<u64, V>` to `HashMap<DiscoveryInstanceId, V>` keyed by full identity (namespace, component, endpoint, instance_id, model_suffix) to prevent cross-endpoint aliasing on broader queries like `AllModels`
- Add `collapse_by_instance_id()` to flatten back to `HashMap<u64, V>` for consumers, preferring base model (suffix=None)
- Fix `MockDiscovery::unregister()` to match by full identity instead of bare instance_id
- Add no-op publish guard: skip `tx.send()` when the collapsed worker view is unchanged, avoiding unnecessary downstream wakeups
- Add test: register base + lora-a + lora-b, unregister lora-a, verify base persists; unregister base, verify lora-b is fallback
- Add test: same worker on two endpoints via AllModels, remove one endpoint, verify other survives

#### Where should the reviewer start?

`lib/runtime/src/discovery/utils.rs`, then `lib/runtime/src/discovery/mock.rs`

#### Related Issues:

Fixes #7758

/coderabbit profile chill

### CODE REVIEW

File: lib/runtime/src/discovery/mock.rs [hunk 1]
```diff
@@ -170,13 +170,13 @@ impl Discovery for MockDiscovery {
     }
 
     async fn unregister(&self, instance: DiscoveryInstance) -> Result<()> {
-        let instance_id = instance.instance_id();
```
Comment (biswapanda) [inline lib/runtime/src/discovery/mock.rs:173]: @mohammedabdulwahhab , previously you changed usage from  `id()` to `instance.id()` right?

File: lib/runtime/src/discovery/utils.rs [hunk 2]
```diff
@@ -38,6 +38,23 @@ use super::{DiscoveryEvent, DiscoveryInstance, DiscoveryStream};
...
+    state: &std::collections::HashMap<(u64, Option<String>), V>,
+) -> std::collections::HashMap<u64, V> {
+    let mut result = std::collections::HashMap::new();
+    for ((id, suffix), val) in state {
+        if suffix.is_none() || !result.contains_key(id) {
+            result.insert(*id, val.clone());
+        }
+    }
+    result
+}
```
[the remark this answers is not in the document]
Comment (keivenchang) [reply lib/runtime/src/discovery/utils.rs]: good catch — fixed in 1055234. internal state is now keyed by full `DiscoveryInstanceId` instead of `(u64, Option<String>)`, so entries from different endpoints dont alias anymore even when they share the same worker id. added `test_all_models_cross_endpoint_no_alias` that actualy fails on the old keying (`state={}`) and passes with the fix.

File: lib/runtime/src/discovery/mock.rs (hunk 1 above)
Comment (keivenchang) [reply lib/runtime/src/discovery/mock.rs:173]: hey — yeah that was me actually, not Mohammed. the distinction is `instance_id()` returns the bare `u64` worker id, while `id()` returns the full `DiscoveryInstanceId` which includes namespace/component/endpoint/suffix. the old code matched by just the u64 so unregistering any variant (e.g. a lora adapter) would wipe every entry sharing that worker id. switching to `id()` makes unregister match by full identity so only the exact registration gets removed.

Comment (biswapanda) [reply lib/runtime/src/discovery/mock.rs:173]: sounds good. Thanks

File: lib/runtime/src/discovery/utils.rs [hunk 3]
```diff
@@ -77,17 +105,36 @@ where
...
+                        instance_id,
+                        ?key,
+                        state_len = state.len(),
+                        "watch_and_extract_field: inserting instance"
+                    );
+
+                    state.insert(key, value);
+
+                    let collapsed = collapse_by_instance_id(&state);
+                    if tx.send(collapsed).is_err() {
```
Comment (biswapanda) [inline lib/runtime/src/discovery/utils.rs]: The functional fix looks correct, but I’d recommend adding a no-op publish guard here. It keeps the control-path overhead bounded and avoids waking downstream watchers (less messages over network) when the
  collapsed worker view is unchanged.

Comment (biswapanda) [reply lib/runtime/src/discovery/utils.rs]: every add/remove event recomputes collapsed and unconditionally calls
  tx.send(collapsed). With the new composite-key state, that means each event now pays for a full collapse_by_instance_id(&state) pass and a fresh HashMap<u64, V> allocation, even
  when the externally visible per-worker map did not change. A concrete case is removing a non-selected LoRA while the base model or another LoRA still remains for that worker.

  That local cost is probably acceptable on its own because this is a control path, not a request hot path. The more important impact is downstream: every no-op send wakes consumers
  that do real work in dynamo/lib/llm/src/discovery/runtime_configs.rs:49 and dynamo/lib/llm/src/discovery/worker_monitor.rs:543.

  Recommendation
  Gate publication on visible-state changes only. The minimal fix is to compare collapsed against the current watched value before sending:

```
  let collapsed = collapse_by_instance_id(&state);
  if *tx.borrow() != collapsed {
      if tx.send(collapsed).is_err() {
          break;
      }
  }
```
  That is concurrency-safe in the current design because this helper has a single writer task. It will not remove the collapse_by_instance_id rebuild cost, but it will suppress no-
  op notifications and reduce downstream recomputation. If you want a more future-proof version, prefer watch::Sender::send_if_modified.

Comment (keivenchang) [reply lib/runtime/src/discovery/utils.rs]: good call — added in b89eb63. skips `tx.send()` when the collapsed view is unchanged, so adding a lora when the base model already represents the worker (or removing one that doesnt affect the collapsed output) wont wake downstream watchers.

**Review by biswapanda — APPROVED** [review]

File: lib/runtime/src/discovery/utils.rs (hunk 3 above)
Comment (biswapanda) [reply lib/runtime/src/discovery/utils.rs]: Thank you for quick fix
