### PR TITLE
fix(dynamo-llm): Use HF_TOKEN env var

### LINKED ISSUE #286: Not able run model
**dynamo run in=text out=vllm meta-llama/Llama-3.2-3B-Instruct**

ERROR dynamo_runtime::worker: Application shutdown with error: Failed to download file 'USE_POLICY.md' from model 'meta-llama/Llama-3.2-3B-Instruct': request error: HTTP status client error (401 Unauthorized) for url (https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct/resolve/main/USE_POLICY.md)
Error: Failed to download file 'USE_POLICY.md' from model 'meta-llama/Llama-3.2-3B-Instruct': request error: HTTP status client error (401 Unauthorized) for url (https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct/resolve/main/USE_POLICY.md)

i have already set HF_HOME and HF_TOKEN

### PR DESCRIPTION
**Pull request by grahamking**
Fixes #286

## Summary by CodeRabbit

- **New Features**
  - Added support for authenticated API access using a Hugging Face token from an environment variable.
- **Chores**
  - Expanded the list of files ignored during model downloads to include "LICENSE.txt" and "USE_POLICY.md".

### CODE REVIEW

File: lib/llm/src/hub.rs [hunk 1]
```diff
@@ -14,15 +14,28 @@
...
 /// Attempt to download a model from Hugging Face
 /// Returns the directory it is in
 pub async fn from_hf(name: impl AsRef<Path>) -> anyhow::Result<PathBuf> {
     let name = name.as_ref();
-    let api = ApiBuilder::new().with_progress(true).build()?;
+    let token = env::var(HF_TOKEN_ENV_VAR).ok();
+    let api = ApiBuilder::new()
+        .with_progress(true)
+        .with_token(token)
+        .build()?;
```
Comment (rmccorm4) [inline lib/llm/src/hub.rs:38]: Sanity checking this works when the env var isn't set as well? 

Seems like it should:
- `env::var("HF_TOKEN").ok()` -> return Some if value, or None if err/no_value
- `with_token(Option<token>)` will only include token in header if Some(token): https://docs.rs/hf-hub/0.4.2/src/hf_hub/api/tokio.rs.html#352

**Review by jthomson04 — APPROVED** [review]

**Review by rmccorm4 — APPROVED** [review]

**Review by GuanLuo — APPROVED** [review]
