### PR TITLE
fix: reject prompts exceeding max_seq_len with HTTP 400

### LINKED ISSUE #6605: [dynamo][release/1.0.0] Prompts exceeding max_seq_len should return HTTP 400, not crash through engine as 500
## Bug Description

When a prompt's token count exceeds `max_seq_len`, Dynamo does **no pre-flight validation** and passes the request directly to TRT-LLM, which then fails internally with a `ValueError`. The error propagates back as an HTTP 500 Internal Server Error instead of an HTTP 400 Bad Request.

This is a missing input validation bug — oversized prompts should be rejected early with a clear 4xx error, not allowed to reach the backend engine.

## Error Output

```
2026-02-25T23:46:55.175899Z  WARN handler_base.generate_locally: Request unknown-id error: `default_max_tokens` (-93) must be greater than 0, `default_max_tokens` (-93) = max_seq_len (16385) - `splited_prompt_len` (16478) - `query_token_len` (0)

[02/25/2026-23:47:37] [TRT-LLM] [E] submit request failed: `default_max_tokens` (-93) must be greater than 0, `default_max_tokens` (-93) = max_seq_len (16385) - `splited_prompt_len` (16478) - `query_token_len` (0)

Traceback (most recent call last):
  File "/opt/dynamo/venv/lib/python3.12/site-packages/tensorrt_llm/executor/base_worker.py", line 526, in _enqueue_request
    max_tokens=_deduce_max_tokens(
  File "/opt/dynamo/venv/lib/python3.12/site-packages/tensorrt_llm/executor/base_worker.py", line 501, in _deduce_max_tokens
    raise ValueError(
ValueError: `default_max_tokens` (-93) must be greater than 0, `default_max_tokens` (-93) = max_seq_len (16385) - `splited_prompt_len` (16478) - `query_token_len` (0)
```

## Root Cause Analysis

Three layers of missing validation:

### 1. Rust preprocessor (`lib/llm/src/preprocessor.rs`) — no guard
The preprocessor tokenizes the input but **never compares token count against `max_seq_len`/`max_model_len`**. The request passes through unchecked.

### 2. Python handler (`components/src/dynamo/trtllm/request_handlers/handler_base.py`) — no guard
`generate_locally()` calls `self.engine.llm.generate_async()` without checking if `len(token_ids) >= max_seq_len`. TRT-LLM's internal `_deduce_max_tokens` computes a negative value and raises `ValueError`.

### 3. Error classification (`lib/llm/src/http/service/openai.rs`) — wrong status code
`extract_backend_error_if_present()` defaults to HTTP 500 because TRT-LLM returns a plain error string, not a JSON payload with a `code` field. Even when the error makes it back, it's classified as a server error instead of a client error.

## Expected Behavior

Following OpenAI API conventions, the response should be:

```json
{
  "error": {
    "message": "This model's maximum context length is 16384 tokens. However, your messages resulted in 16478 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "code": "context_length_exceeded"
  }
}
```

With **HTTP 400 Bad Request** status code.

## Proposed Fix

1. **Pre-flight validation in the Rust preprocessor** (best): After tokenization, compare token count against `max_model_len` from the model card. Return HTTP 400 immediately — never send the request downstream. This also applies to vLLM and SGLang backends.

2. **Pre-flight validation in the Python TRT-LLM handler** (quick fix): Add a guard in `generate_locally()` before `generate_async()` to check `len(token_ids) >= max_seq_len` and yield a proper error with status code 400.

3. **Error classification safety net**: In `extract_backend_error_if_present()`, pattern-match on known input validation errors (e.g., `max_seq_len`, `must be greater than 0`) and return 400 instead of 500.

## Environment

- **Model**: gpt-oss-20b (TRT-LLM backend)
- **Config**: `max_seq_len: 16384` via DynamoGraphDeployment operator
- **Dynamo version**: latest main branch (Feb 2026)

## Impact

- Users receive confusing 500 errors for a simple input validation issue
- Wasted GPU compute — the request travels all the way to TRT-LLM before failing
- No actionable error message for API consumers to fix their request
- Applies to all backends (TRT-LLM, vLLM, SGLang) since validation is missing at the Dynamo layer

### PR DESCRIPTION
**Pull request by nv-yna**
## Summary

- Add pre-flight token count validation in the Rust preprocessor to reject prompts exceeding `context_length` with HTTP 400 and an actionable error message
- Pass runtime-configured context limits from all three backends (TRT-LLM, vLLM, SGLang) to `register_model()`, so the preprocessor validates against the **actual engine limit**, not just the model's architectural `max_position_embeddings`
- Error message matches OpenAI API format: `"This model's maximum context length is {max} tokens. However, your messages resulted in {count} tokens. Please reduce the length of the messages."`

## Problem

Previously, oversized prompts had no pre-flight validation. They passed through to the backend engine and returned HTTP 500. The MDC's `context_length` defaulted to `max_position_embeddings` from config.json, but operators often deploy with a lower runtime limit (e.g., `--max-seq-len 16384` on a 128K model). The preprocessor had no way to know the real limit.

### Rust preprocessor validation (`lib/llm/src/preprocessor.rs`)
- Store `context_length` in `OpenAIPreprocessor`, set from the MDC
- After tokenization in `gather_tokens()`, validate token count against `context_length`
- Return `HttpError{code: 400}` with OpenAI-compatible error message
- All input paths covered: text, tokens, single, batch

### Backend registration (pass runtime limit to MDC)
- **TRT-LLM** (`trtllm/workers/llm_worker.py`): Pass `context_length=config.max_seq_len`
- **vLLM** (`vllm/main.py`): Pass `context_length=vllm_config.model_config.max_model_len`
- **SGLang** (`sglang/register.py`): Pass `context_length=server_args.context_length`

These override the MDC's default `max_position_embeddings` with the engine's actual runtime limit.

### Edge cases
- `context_length == 0` (unconfigured): validation skipped
- Pre-tokenized input (token IDs passed directly): still validated

Closes #6605

## Test plan

- [x] `cargo check -p dynamo-llm` — compiles
- [x] `cargo test -p dynamo-llm` — all tests pass
- [x] `pre-commit run --all-files` — all checks pass
- [x] Unit tests: prompt exceeding context_length returns `HttpError{code: 400}`
- [x] Unit tests: prompt within context_length succeeds
- [x] Unit tests: `context_length=0` skips validation
- [ ] Manual E2E: send a prompt with more tokens than `max_seq_len` and verify HTTP 400 with expected error message

### CODE REVIEW

File: lib/llm/src/preprocessor.rs [hunk 1]
```diff
@@ -522,6 +535,24 @@ impl OpenAIPreprocessor {
...
+                return Err(HttpError {
+                    code: 400,
+                    message: format!(
+                        "This model's maximum context length is {} tokens. \
+                         However, your messages resulted in {} tokens. \
+                         Please reduce the length of the messages.",
+                        max_len, count,
+                    ),
+                }
+                .into());
```
[the remark this answers is not in the document]
Comment (nv-yna) [reply lib/llm/src/preprocessor.rs]: The current error message limits its capability to fully report exactly like open ai. It will be a larger conversation to reach that state.

File: components/src/dynamo/trtllm/workers/llm_worker.py [hunk 2]
```diff
@@ -456,6 +456,7 @@ async def init_llm_worker(
                 endpoint,
                 config.model,
                 config.served_model_name,
+                context_length=config.max_seq_len,
```
Comment (rmccorm4) [inline components/src/dynamo/trtllm/workers/llm_worker.py:459]: Should this be `max_input_len` instead of max_seq_len? I believe `max_seq_len` is ISL+OSL. Would be good to double check with TRTLLM experts

https://github.com/NVIDIA/TensorRT-LLM/blob/80aa8caf441cfa5abb4d13ac90a8353edac7c03d/tensorrt_llm/llmapi/llm_args.py#L2185

Comment (nv-yna) [reply components/src/dynamo/trtllm/workers/llm_worker.py:459]: `max_seq_len` is ISL+OSL, so as other args touched in this PR for sglang and vllm. I think it's fair to just check  prompt length against the whole context length because if the prompt itself already consumes all the context length, we should directly reject without question since the worker won't be able to do anything anyways.

File: lib/llm/src/preprocessor.rs [hunk 3]
```diff
@@ -522,6 +535,24 @@ impl OpenAIPreprocessor {
                 }
             }
         }
+
+        // Validate prompt token count against model's context length
```
Comment (tanmayv25) [inline lib/llm/src/preprocessor.rs:545]: Can you move the validation to a new function? possibly `validate_token_count` ?
We can call this function after gather_token() is complete.

File: lib/llm/src/preprocessor.rs [hunk 4]
```diff
@@ -522,6 +535,24 @@ impl OpenAIPreprocessor {
...
+        if let Some(count) = token_count {
+            let max_len = self.context_length as usize;
+            if max_len > 0 && count >= max_len {
+                return Err(HttpError {
```
Comment (tanmayv25) [inline lib/llm/src/preprocessor.rs]: I don't think we should be exposing HttpError in preprocessor.rs. We should return an error as an instance of DynamoError. 
We can convert it to HttpError with specific code in HTTP handler layer.

Comment (tanmayv25) [reply lib/llm/src/preprocessor.rs]: We can have InvalidInput as a ErrorType.
https://github.com/ai-dynamo/dynamo/blob/d9657b34e4594c04a29ea4e56dbe142aa65d34b2/lib/runtime/src/error.rs#L43

The reason I am asking is that we also have a grpc frontend that may not be able to handle this error type.

File: components/src/dynamo/vllm/main.py [hunk 5]
```diff
@@ -586,6 +586,9 @@ async def register_vllm_model(
         generate_endpoint,
         config.model,
         config.served_model_name,
+        context_length=getattr(
```
Comment (biswapanda) [inline components/src/dynamo/vllm/main.py]: This is bit confusing. Should we annotate `register_model` with proper type ([VllmConfig](https://docs.vllm.ai/en/stable/configuration/engine_args/#vllmconfig)) for vllm_config object

File: components/src/dynamo/sglang/register.py [hunk 6]
```diff
@@ -56,6 +56,7 @@ async def _register_model_with_runtime_config(
             endpoint,
             server_args.model_path,
             server_args.served_model_name,
+            context_length=getattr(server_args, "context_length", None),
```
Comment (biswapanda) [inline components/src/dynamo/sglang/register.py]: Let's use `server_args.context_length` here? 

https://github.com/sgl-project/sglang/blob/1a32c0db4d4a32edd43b88c54e351a1b2c8a2140/python/sglang/srt/server_args.py#L295

File: lib/llm/src/preprocessor.rs [hunk 7]
```diff
@@ -146,6 +148,8 @@ pub struct OpenAIPreprocessor {
     runtime_config: crate::local_model::runtime_config::ModelRuntimeConfig,
     tool_call_parser: Option<String>,
     media_loader: Option<MediaLoader>,
+    /// Max context length (in tokens) this model can handle, from ModelDeploymentCard
+    context_length: u32,
```
Comment (biswapanda) [inline lib/llm/src/preprocessor.rs:152]: Should this be optional `Option<u32>` ?

File: lib/llm/src/preprocessor.rs (hunk 4 above)
Comment (biswapanda) [reply lib/llm/src/preprocessor.rs]: +1 we can return a `anyhow::Result` here.

File: lib/llm/src/preprocessor.rs [hunk 8]
```diff
@@ -539,7 +539,7 @@ impl OpenAIPreprocessor {
         // Validate prompt token count against model's context length
         if let Some(count) = token_count {
             let max_len = self.context_length as usize;
-            if max_len > 0 && count > max_len {
+            if max_len > 0 && count >= max_len {
```
Comment (biswapanda) [inline lib/llm/src/preprocessor.rs]: Nice 👍

File: components/src/dynamo/vllm/main.py (hunk 5 above)
Comment (nv-yna) [reply components/src/dynamo/vllm/main.py]: sgtm

File: components/src/dynamo/sglang/register.py (hunk 6 above)
Comment (nv-yna) [reply components/src/dynamo/sglang/register.py]: thx, done

File: lib/llm/src/preprocessor.rs (hunk 7 above)
Comment (nv-yna) [reply lib/llm/src/preprocessor.rs:152]: Thanks to AI. It's amazing how much time it saves for me to figure this out...

The value comes from [MDC](https://github.com/ai-dynamo/dynamo/pull/6635/changes#diff-74d685c1cb27cae5e2a24b491729567c173effa09f93b48946688487a5299b31R192-R193), whose value is defined as [non-optional u32](https://github.com/ai-dynamo/dynamo/blob/main/lib/llm/src/model_card.rs#L220) and [value 0](https://github.com/ai-dynamo/dynamo/blob/main/lib/llm/src/model_card.rs#L633) is a default that meant for using engine default value.

Then there is a question where maybe it's better to use None and mark everything as Option<u32>. If you agree with this, I'll use another PR to address this.

File: lib/llm/src/preprocessor.rs (hunk 3 above)
Comment (nv-yna) [reply lib/llm/src/preprocessor.rs:545]: sg. done

File: lib/llm/src/preprocessor.rs (hunk 4 above)
Comment (nv-yna) [reply lib/llm/src/preprocessor.rs]: PTAL. Not sure if it aligns with what you had in mind

**Comment by itay** [comment]
@grahamking how would this work with the python processing path?

File: lib/llm/tests/preprocessor.rs [hunk 9]
```diff
@@ -622,3 +622,131 @@ async fn test_media_url_passthrough(#[case] media_chunks: &[(&str, usize)]) {
...
+        );
+        assert!(
+            dynamo_err.message().contains("Please reduce the length"),
+            "error message should tell user what to do, got: {}",
+            dynamo_err.message()
+        );
+    }
+
+    #[tokio::test]
+    async fn test_prompt_within_context_length_succeeds() {
```
Comment (grahamking) [inline lib/llm/tests/preprocessor.rs]: Can delete this one, that's already covered by other test.

**Comment by grahamking** [comment]
> They passed through to the backend engine, which crashed with a ValueError and returned HTTP 500

The crash sounds like the more important problem. Can you give more details?

There's no harm in merging this to have more up-front validation, but that crash is the core issue - and definitely a 500.

**Review by biswapanda — APPROVED** [review]
lgtm!
 please address @grahamking's reviews before merge.

**Review by grahamking — APPROVED** [review]

**Comment by grahamking** [comment]
> @grahamking how would this work with the python processing path?

This PR changes parts that the vllm processor replaces. Either vllm will already be handling it for us, or we'll need to do the work there too.

File: lib/llm/tests/preprocessor.rs (hunk 9 above)
Comment (nv-yna) [reply lib/llm/tests/preprocessor.rs]: done

File: components/src/dynamo/vllm/main.py [hunk 10]
```diff
@@ -577,6 +577,7 @@ async def register_vllm_model(
         generate_endpoint,
         config.model,
         config.served_model_name,
+        context_length=vllm_config.model_config.max_model_len,
```
Comment (sytianhe) [inline components/src/dynamo/vllm/main.py:580]: what happen if we don't define this in model config but using the model default?

Comment (nv-yna) [reply components/src/dynamo/vllm/main.py:580]: When the user doesn't set --max-model-len, vLLM derives it automatically in _get_and_verify_max_len.
It scans the model's config for keys like max_position_embeddings, n_positions, max_seq_len, etc., takes the minimum, and assigns it:
```
  if max_model_len is None:
      max_model_len = int(derived_max_model_len)
```

So vllm_config.model_config.max_model_len is either reflects the user's explicit --max-model-len or the value derived from the model config.

https://github.com/vllm-project/vllm/blob/d1c6799b8870e513bf4f2305cbf6cda9fc3d773b/vllm/config.py#L1942-L1943

**Review by tanmayv25 — APPROVED** [review]

File: components/src/dynamo/vllm/main.py (hunk 10 above)
Comment (sytianhe) [reply components/src/dynamo/vllm/main.py:580]: And I assume trt and svlang will do the same right?
