### PR TITLE
fix: Only check model name on etcd-registered endpoints

### LINKED ISSUE #1234: [BUG]: KvMetricsPublisher doesn't support two workers from python
### Describe the Bug

When I use dynamo-run I want to be able to do this workflow:
**Terminal 1:  - `DYN_LOG=debug ./dynamo-run in=http out=dyn --router-mode kv`
**Terminal 2:  - `python vllm_v1_inc.py`
**Terminal 3: - `python vllm_v1_inc.py`

### Steps to Reproduce

Doing the above results in

```python vllm_v1_inc.py
INFO 05-28 05:43:42 [__init__.py:248] Automatically detected platform cuda.
BLOCK SIZE: 16
Traceback (most recent call last):
  File "/home/ubuntu/dynamo/launch/dynamo-run/src/subprocess/vllm_v1_inc.py", line 332, in <module>
    asyncio.run(worker())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/dynamo/lib/bindings/python/src/dynamo/runtime/__init__.py", line 41, in wrapper
    await func(runtime, *args, **kwargs)
  File "/home/ubuntu/dynamo/launch/dynamo-run/src/subprocess/vllm_v1_inc.py", line 165, in worker
    await init(runtime, cmd_line_args())
  File "/home/ubuntu/dynamo/launch/dynamo-run/src/subprocess/vllm_v1_inc.py", line 177, in init
    await register_llm(
Exception: No ModelEntry in etcd for key models/dynamo_backend_load_metrics-694d96f39ab1f91b
```

### Expected Behavior

Expect both models to be registered with front-end and for KV Routing to occur between the two of them.

### Actual Behavior

Error.

### Environment

System Information:
OS: Ubuntu 24.04
Glibc Version: 2.39
GCC Version: 13.3.0
Cmake Version: 3.28.3
Rust Version: 1.87.0
Docker Version: N/A

CPU Information:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               24
On-line CPU(s) list:                  0-23
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz
CPU family:                           6
Model:                                85
Thread(s) per core:                   2
Core(s) per socket:                   12
Socket(s):                            1
Stepping:                             7
CPU(s) scaling MHz:                   30%
CPU max MHz:                          4800.0000
CPU min MHz:                          1200.0000
BogoMIPS:                             6999.82
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req vnmi avx512_vnni md_clear flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            384 KiB (12 instances)
L1i cache:                            384 KiB (12 instances)
L2 cache:                             12 MiB (12 instances)
L3 cache:                             19.3 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-23
Vulnerability Gather data sampling:   Mitigation; Microcode
Vulnerability Itlb multihit:          KVM: Mitigation: VMX disabled
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; Enhanced IBRS
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Mitigation; TSX disabled

Python Version: 3.12.3
Python Platform: Linux-6.8.0-58-generic-x86_64-with-glibc2.39

Python Packages:
ai-dynamo: 0.2.1
ai-dynamo-runtime: 0.2.1
ai-dynamo-vllm: Not installed
genai-perf: Not installed
nixl: 0.2.1
numpy: 1.26.4
nvidia-cublas-cu12: 12.6.4.1
nvidia-cuda-cupti-cu12: 12.6.80
nvidia-cuda-nvrtc-cu12: 12.6.77
nvidia-cuda-runtime-cu12: 12.6.77
nvidia-cudnn-cu12: 9.5.1.17
nvidia-cufft-cu12: 11.3.0.4
nvidia-curand-cu12: 10.3.7.77
nvidia-cusolver-cu12: 11.7.1.2
nvidia-cusparse-cu12: 12.5.4.2
nvidia-ml-py: 12.575.51
nvidia-nccl-cu12: 2.26.2
nvidia-nvjitlink-cu12: 12.6.85
nvidia-nvtx-cu12: 12.6.77
pyzmq: 26.4.0
tensorrt_llm: Not installed
torch: 2.7.0
torchaudio: 2.7.0
transformers: 4.52.3
tritonclient: 2.53.0

### Additional Context

This is occurring in my v1 branch. I am assuming something similar would happen with v0, but I could be mistaken.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by jthomson04**
Fixes kv routing to multiple python workers. After creating one worker, creating another worker would cause etcd errors. This was because we were checking model names of every endpoint for the component. Some of the endpoints (such as load_metrics) aren't published to etcd, so this would fail. Instead, we can just check the model name for endpoints registered to etcd.

Closes: #1234 

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved uniqueness checks to only apply to component instances with a "generate" endpoint, reducing unnecessary duplicate detection for other endpoints.
  - Enhanced error handling during model name uniqueness verification to avoid interruptions from network entry loading issues.

### CODE REVIEW

File: lib/llm/src/local_model.rs [hunk 1]
```diff
@@ -184,9 +184,11 @@ impl LocalModel {
         };
         for endpoint_info in component.list_instances().await? {
             let network_name: ModelNetworkName = (&endpoint_info).into();
-            let entry = network_name.load_entry(&etcd_client).await?;
-            if entry.name != model_name {
-                anyhow::bail!("Duplicate component. Attempt to register model {model_name} at {component}, which is already used by {network_name} running model {}.", entry.name);
+            if endpoint_info.endpoint == "generate" {
```
Comment (rmccorm4) [inline lib/llm/src/local_model.rs]: If no one else has a more general solution readily available - would it make sense to instead invert this check to exclude load_metrics?
```
// Ideally re-use constant instead of string literal
if endpoint_info.endpoint != "load_metrics"
...
```

"load_metrics" is a hard-coded thing in the codebase currently, whereas "generate" is just a common endpoint name, but can be arbitrarily any name chosen by user.

Comment (alec-flowers) [reply lib/llm/src/local_model.rs]: Yea I'm also not sure the best way to handle this. If we want to "auto-discover" which is what is happening then I guess it makes sense to define the standard for what is auto-discoverable. We will need to document that.

For example in the python examples back in the day I had a generate_completion and generate_chat endpoint. This wouldn't have matched such logic and we wouldn't have discovered it.

Comment (alec-flowers) [reply lib/llm/src/local_model.rs]: What if we publish every endpoint to etcd with the model name that it is tied too?

Comment (alec-flowers) [reply lib/llm/src/local_model.rs]: Then the check does what its supposed to, it ensures the components endpoints are for the right model. Then I guess we would need another field to find to select which endpoint is the right one to actually do our routing to. But that would be fine.

Comment (alec-flowers) [reply lib/llm/src/local_model.rs]: /// We cannot have multiple models with the same component name.
///
/// Returns an error if there is already a component by this name serving a different model.

I think we should check etcd, if the endpoint doesn't have an entry in etcd, ignore it. 
If the endpoint has an entry in etcd, but no model_name, ignore it.
If it has an entry in etcd and a model name, then check it. If same name then ok, if different then bail. 

This way we are specifying this logic will only work for endpoints that are registered in etcd with an entry for model_name.

Comment (ryanolson) [reply lib/llm/src/local_model.rs]: I'm firmly of the belief that each component should write something to etcd when it creates a service. this value should be idempotent across replicas, i.e. `{namespace}.{component}` addresses.

In this manner, creating a service should use an etcd `create_or_validate` method, which will either:
- atomically create an entry specific to `{namespace}.{component}`
- or validate the entry created by the first arriver is exactly the same as the entry it would have created - or throw an error.

There should be a generic component entry AND optionally a component specific entry.  If the component were a LLM Backend or a Router, it would also write any information about its specific state to the type specific entry.

In this manner, workers could look for routers and read the router's config entry or vise versa.

**Review by grahamking — CHANGES_REQUESTED** [review]
We can't hard code an endpoint name like this. Adding a blocking "request changes" until we can figure it out in the thread Ryan started.

File: lib/llm/src/local_model.rs (hunk 1 above)
Comment (jthomson04) [reply lib/llm/src/local_model.rs]: > I think we should check etcd, if the endpoint doesn't have an entry in etcd, ignore it. If the endpoint has an entry in etcd, but no model_name, ignore it. If it has an entry in etcd and a model name, then check it. If same name then ok, if different then bail.
> 
> This way we are specifying this logic will only work for endpoints that are registered in etcd with an entry for model_name.

At least for the time being, that's probably the right way to go

**Comment by grahamking** [comment]
Can you update the title and description?

**Review by grahamking — APPROVED** [review]
